######################################################################
# Automatically generated by qmake (2.00a) Sun Sep 25 14:43:15 2005
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += GLDemo.cpp
QT += opengl
