all: GrayscaleImage.cpp RGBImage.cpp Color.cpp RGBImageGC.cpp Rect2D.cpp Point2D.cpp BitmapFont.cpp GraphicsContext.cpp PostScriptGC.cpp testmain.cpp
	g++ -o testGC -g GrayscaleImage.cpp RGBImage.cpp Color.cpp RGBImageGC.cpp Rect2D.cpp Point2D.cpp BitmapFont.cpp PostScriptGC.cpp  testmain.cpp
