all: GrayscaleImage.cpp RGBImage.cpp Color.cpp RGBImageGC.cpp Rect2D.cpp Point2D.cpp BitmapFont.cpp GraphicsContext.cpp testmain.cpp	
	g++ -o testGC -g -Wall GrayscaleImage.cpp RGBImage.cpp Color.cpp RGBImageGC.cpp Rect2D.cpp Point2D.cpp BitmapFont.cpp testmain.cpp
