Import('env')
list = Split("""OptFun.cpp 
LoadFN.cpp 
Interp1D.cpp 
lmdif1.f 
lmdif.f 
lmpar.f 
qrfac.f 
dpmpar.f 
enorm.f 
qrsolv.f 
fdjac2.f 
FNFun.cpp 
erf.f 
derf.f 
ei.f 
dei.f 
daw.f 
ddaw.f 
psi.f 
dpsi.f 
gamma.f 
dgamma.f 
algama.f 
dlgama.f""")
env.Library('FN', list, CPPPATH = ['.','../libFreeMat'])

