Import('env')
list = Split("""OptFun.cpp 
LoadFN.cpp 
Interp1D.cpp 
lmdif1.c 
lmdif.c 
lmpar.c 
qrfac.c 
dpmpar.c 
enorm.c 
qrsolv.c 
fdjac2.c 
FNFun.cpp 
erf.c 
derf.c 
ei.c 
dei.c 
daw.c 
ddaw.c 
psi.c 
dpsi.c 
gamma.c 
dgamma.c 
algama.c 
dlgama.c""")
Library('FN', list, CPPPATH = ['.','../libFreeMat'])

