#!/bin/sh
#
# Improvements to this script:
#   1. Update build number in WalkTree.cpp
#   2. Reconfigure and remake for bundle installations?
rm -rf build
./bootstrap
mkdir build
cd build
../configure
make
make check
cd ..
./makehelp build/tools/helpgen/helpgen .
cd build
make
make distcheck
tools/disttool/makepkg --linux . .. $QTDIR
