% Regression test function (black box) for flipdim
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_array_flipdim
  bbtest_success = 1;
NumErrors = 0;
try
  x = int32(rand(4,5,3)*10)
catch
  NumErrors = NumErrors + 1;
end
try
  flipdim(x,1)
catch
  NumErrors = NumErrors + 1;
end
try
  flipdim(x,2)
catch
  NumErrors = NumErrors + 1;
end
try
  flipdim(x,3)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
