% Regression test function (black box) for ylim
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_handle_ylim
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(-1,1);
catch
  NumErrors = NumErrors + 1;
end
try
  y = sin(2*pi*x);
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,y,'r-');
catch
  NumErrors = NumErrors + 1;
end
try
  ylim  % what are the current limits?
catch
  NumErrors = NumErrors + 1;
end
try
  mprint ylim1
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  plot(x,y,'r-')
catch
  NumErrors = NumErrors + 1;
end
try
  ylim([-0.2,0.2])
catch
  NumErrors = NumErrors + 1;
end
try
  mprint ylim2
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  plot(x,y,'r-');
catch
  NumErrors = NumErrors + 1;
end
try
  ylim([0,inf])
catch
  NumErrors = NumErrors + 1;
end
try
  mprint ylim3
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
