% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_getprintlimit
  bbtest_success = 1;
NumErrors = 0;
try
  A = randn(100,1);

catch
  NumErrors = NumErrors + 1;
end
try
  n = getprintlimit

catch
  NumErrors = NumErrors + 1;
end
try
  setprintlimit(5);

catch
  NumErrors = NumErrors + 1;
end
try
  A

catch
  NumErrors = NumErrors + 1;
end
try
  setprintlimit(n)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
