% Regression test function (black box) for isset
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_inspection_isset
  bbtest_success = 1;
NumErrors = 0;
try
  who
catch
  NumErrors = NumErrors + 1;
end
try
  isset('a')
catch
  NumErrors = NumErrors + 1;
end
try
  a = [];
catch
  NumErrors = NumErrors + 1;
end
try
  isset('a')
catch
  NumErrors = NumErrors + 1;
end
try
  a = 2;
catch
  NumErrors = NumErrors + 1;
end
try
  isset('a')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
