% Regression test function (black box) for norm
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_array_norm
  bbtest_success = 1;
NumErrors = 0;
try
  A = float(rand(3,4))
catch
  NumErrors = NumErrors + 1;
end
try
  norm(A,1)
catch
  NumErrors = NumErrors + 1;
end
try
  norm(A,2)
catch
  NumErrors = NumErrors + 1;
end
try
  norm(A,inf)
catch
  NumErrors = NumErrors + 1;
end
try
  norm(A,'fro')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  A = float(rand(4,1))
catch
  NumErrors = NumErrors + 1;
end
try
  norm(A,1)
catch
  NumErrors = NumErrors + 1;
end
try
  norm(A,2)
catch
  NumErrors = NumErrors + 1;
end
try
  norm(A,7)
catch
  NumErrors = NumErrors + 1;
end
try
  norm(A,inf)
catch
  NumErrors = NumErrors + 1;
end
try
  norm(A,-inf)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
