% Regression test function (black box) for spy
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_sparse_spy
  bbtest_success = 1;
NumErrors = 0;
try
  y = sprand(1000,1000,.001);
catch
  NumErrors = NumErrors + 1;
end
try
  spy(y,'ro')
catch
  NumErrors = NumErrors + 1;
end
try
  mprint spy1
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  A = sparse(1000,1000);
catch
  NumErrors = NumErrors + 1;
end
try
  for i=1:25; A((1:40) + 40*(i-1),(1:40) + 40*(i-1)) = 1; end;
catch
  NumErrors = NumErrors + 1;
end
try
  spy(A,'gx')
catch
  NumErrors = NumErrors + 1;
end
try
  mprint spy2
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
