% Regression test function (black box) for varargout
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_functions_varargout
  bbtest_success = 1;
NumErrors = 0;
try
  [c1] = varoutfunc
catch
  NumErrors = NumErrors + 1;
end
try
  [c1,c2] = varoutfunc
catch
  NumErrors = NumErrors + 1;
end
try
  [c1,c2,c3] = varoutfunc
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
