% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_isfield
  bbtest_success = 1;
NumErrors = 0;
try
  a.foo = 32

catch
  NumErrors = NumErrors + 1;
end
try
  a.goo = 64

catch
  NumErrors = NumErrors + 1;
end
try
  isfield(a,'goo')

catch
  NumErrors = NumErrors + 1;
end
try
  isfield(a,'got')

catch
  NumErrors = NumErrors + 1;
end
try
  isfield(pi,'round')

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
