% Regression test function (black box) for coth
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_coth
  bbtest_success = 1;
NumErrors = 0;
try
  x1 = -pi+.01:.01:-.01;
catch
  NumErrors = NumErrors + 1;
end
try
  x2 = .01:.01:pi-.01;
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x1,coth(x1),x2,coth(x2)); grid('on');
catch
  NumErrors = NumErrors + 1;
end
try
  mprint('cothplot');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
