% Regression test function (black box) for deblank
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_string_deblank
  bbtest_success = 1;
NumErrors = 0;
try
  deblank('hello   ')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  deblank({'hello  ','there ','  is  ','  sign  '})
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
