% Regression test function (black box) for nargin
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_functions_nargin
  bbtest_success = 1;
NumErrors = 0;
try
  nargintest(3);
catch
  NumErrors = NumErrors + 1;
end
try
  nargintest(3,'h');
catch
  NumErrors = NumErrors + 1;
end
try
  nargintest(3,'h',1.34);
catch
  NumErrors = NumErrors + 1;
end
try
  nargintest(3,'h',1.34,pi,e);
catch
  NumErrors = NumErrors + 1;
end
try
  nargin('sin')
catch
  NumErrors = NumErrors + 1;
end
try
  y = @sin
catch
  NumErrors = NumErrors + 1;
end
try
  nargin(y)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
