% Regression test function (black box) for global
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_variables_global
  bbtest_success = 1;
NumErrors = 0;
try
  set_global('Hello')
catch
  NumErrors = NumErrors + 1;
end
try
  get_global
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
