% Regression test function (black box) for ndgrid
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_array_ndgrid
  bbtest_success = 1;
NumErrors = 0;
try
  [a,b] = ndgrid(1:2,3:5)
catch
  NumErrors = NumErrors + 1;
end
try
  [a,b,c] = ndgrid(1:2,3:5,0:1)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  [a,b,c] = ndgrid(1:3)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
