% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_log10
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(1,100);

catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,log10(x))

catch
  NumErrors = NumErrors + 1;
end
try
  xlabel('x');

catch
  NumErrors = NumErrors + 1;
end
try
  ylabel('log10(x)');

catch
  NumErrors = NumErrors + 1;
end
try
  mprint('log10plot');

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
