% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_reshape
  bbtest_success = 1;
NumErrors = 0;
try
  a = uint8(1:6)

catch
  NumErrors = NumErrors + 1;
end
try
  reshape(a,2,3)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  a = uint8(1:12)

catch
  NumErrors = NumErrors + 1;
end
try
  reshape(a,[2,3,2])

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  a = [1,6,7;3,4,2]

catch
  NumErrors = NumErrors + 1;
end
try
  reshape(a,3,2)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
