% Regression test function (black box) for sinh
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_sinh
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(-5,5);
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,sinh(x)); grid('on');
catch
  NumErrors = NumErrors + 1;
end
try
  mprint('sinhplot');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
