% Regression test function (black box) for legendre
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_legendre
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(-1,1,30);
catch
  NumErrors = NumErrors + 1;
end
try
  y = legendre(4,x);
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,y); xlabel('x'); ylabel('legendre(4,x)');
catch
  NumErrors = NumErrors + 1;
end
try
  mprint legendre
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
