% Regression test function (black box) for source
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_freemat_source
  bbtest_success = 1;
NumErrors = 0;
try
  clear a b
catch
  NumErrors = NumErrors + 1;
end
try
  source source_test
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
