% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_gamma
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(-5,5);

catch
  NumErrors = NumErrors + 1;
end
try
  y = gamma(x);

catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,y); xlabel('x'); ylabel('gamma(x)');

catch
  NumErrors = NumErrors + 1;
end
try
  axis([-5,5,-5,5]);

catch
  NumErrors = NumErrors + 1;
end
try
  mprint gamma1

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
