% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_sort
  bbtest_success = 1;
NumErrors = 0;
try
  A = int32(10*rand(4,3))

catch
  NumErrors = NumErrors + 1;
end
try
  [B,IX] = sort(A)

catch
  NumErrors = NumErrors + 1;
end
try
  [B,IX] = sort(A,2)

catch
  NumErrors = NumErrors + 1;
end
try
  [B,IX] = sort(A,1,'descend')

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  a = {'hello','abba','goodbye','jockey','cake'}

catch
  NumErrors = NumErrors + 1;
end
try
  b = sort(a)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
