% Regression test function (black box) for ls
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_os_ls
  bbtest_success = 1;
NumErrors = 0;
try
  ls m*.m
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  ls('m*.m')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  ls 'm*.m'
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
