% Regression test function (black box) for isinf
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_inspection_isinf
  bbtest_success = 1;
NumErrors = 0;
try
  a = [1.2 3.4 inf 5]
catch
  NumErrors = NumErrors + 1;
end
try
  isinf(a)
catch
  NumErrors = NumErrors + 1;
end
try
  b = 3./[2 5 0 3 1]
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
