% Regression test function (black box) for type
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_io_type
  bbtest_success = 1;
NumErrors = 0;
try
  type('type')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
