% Regression test function (black box) for strtrim
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_string_strtrim
  bbtest_success = 1;
NumErrors = 0;
try
  strtrim('  lot of blank spaces    ');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  strtrim({'  space','enough ',' for ',''})
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
