% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_strstr
  bbtest_success = 1;
NumErrors = 0;
try
  strstr('hello','lo')

catch
  NumErrors = NumErrors + 1;
end
try
  strstr('quick brown fox','own')

catch
  NumErrors = NumErrors + 1;
end
try
  strstr('free stuff','lunch')

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
