% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_teps
  bbtest_success = 1;
NumErrors = 0;
try
  teps(float(3.4))

catch
  NumErrors = NumErrors + 1;
end
try
  teps(complex(3.4+i*2))

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
