% Regression test function (black box) for clocktotime
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_freemat_clocktotime
  bbtest_success = 1;
NumErrors = 0;
try
  x = clock
catch
  NumErrors = NumErrors + 1;
end
try
  sleep(1)
catch
  NumErrors = NumErrors + 1;
end
try
  y = clock
catch
  NumErrors = NumErrors + 1;
end
try
  clocktotime(y) - clocktotime(x)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
