% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_threadvalue
  bbtest_success = 1;
NumErrors = 0;
try
  a = threadnew;                         % Create the thread

catch
  NumErrors = NumErrors + 1;
end
try
  threadstart(a,'system',1,'ls -lrt /'); % Start the thread

catch
  NumErrors = NumErrors + 1;
end
try
  b = rand(100)\rand(100,1);             % Solve some equations simultaneously

catch
  NumErrors = NumErrors + 1;
end
try
  c = threadvalue(a);                    % Retrieve the file list

catch
  NumErrors = NumErrors + 1;
end
try
  size(c)                                % It is large!

catch
  NumErrors = NumErrors + 1;
end
try
  threadfree(a);

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  a = threadnew

catch
  NumErrors = NumErrors + 1;
end
try
  threadstart(a,'error',0,'Hello world!'); % Will immediately stop due to error

catch
  NumErrors = NumErrors + 1;
end
try
  c = threadvalue(a)                     % The error comes to us

catch
  NumErrors = NumErrors + 1;
end
try
  threadfree(a)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 1) bbtest_success = 0; return; end
