% Regression test function (black box) for rank
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_array_rank
  bbtest_success = 1;
NumErrors = 0;
try
  rank([1,3,2;4,5,6])
catch
  NumErrors = NumErrors + 1;
end
try
  rank([1,2,3;2,4,6])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  A = [1,0;0,eps/2]
catch
  NumErrors = NumErrors + 1;
end
try
  rank(A)
catch
  NumErrors = NumErrors + 1;
end
try
  rank(A,eps/8)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
