% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_atan2
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(-pi,pi);

catch
  NumErrors = NumErrors + 1;
end
try
  sx = sin(x); cx = cos(x);

catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,atan(sx./cx),x,atan2(sx,cx))

catch
  NumErrors = NumErrors + 1;
end
try
  mprint('atan2plot');

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
