% Regression test function (black box) for rem
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_rem
  bbtest_success = 1;
NumErrors = 0;
try
  rem(18,12)
catch
  NumErrors = NumErrors + 1;
end
try
  rem(6,5)
catch
  NumErrors = NumErrors + 1;
end
try
  rem(2*pi,pi)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  rem([1,3,5,2],2)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  rem([9 3 2 0],[1 0 2 2])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
