% Regression test function (black box) for length
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_inspection_length
  bbtest_success = 1;
NumErrors = 0;
try
  x = rand(4,4,3);
catch
  NumErrors = NumErrors + 1;
end
try
  length(x)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
