% Regression test function (black box) for find
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_array_find
  bbtest_success = 1;
NumErrors = 0;
try
  a = [1,2,5,2,4];
catch
  NumErrors = NumErrors + 1;
end
try
  find(a==2)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  A = [1,0,3;0,2,1;3,0,0]
catch
  NumErrors = NumErrors + 1;
end
try
  n = find(A==0)
catch
  NumErrors = NumErrors + 1;
end
try
  A(n) = 5
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  A = [1,0,3;0,2,1;3,0,0]
catch
  NumErrors = NumErrors + 1;
end
try
  A(A==0) = 5
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  A = [1,0,3;0,2,1;3,0,0]
catch
  NumErrors = NumErrors + 1;
end
try
  [r,c] = find(A)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  [r,c,v] = find(A)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
