% Regression test function (black box) for leftdivide
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_operators_leftdivide
  bbtest_success = 1;
NumErrors = 0;
try
  A = [1,1;0,1]
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  B = [3;2]
catch
  NumErrors = NumErrors + 1;
end
try
  Y = A\B
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  A = [1;1]
catch
  NumErrors = NumErrors + 1;
end
try
  B = [2;1]
catch
  NumErrors = NumErrors + 1;
end
try
  A\B
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
