% Regression test function (black box) for e
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_constants_e
  bbtest_success = 1;
NumErrors = 0;
try
  e
catch
  NumErrors = NumErrors + 1;
end
try
  log(e)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
