% Regression test function (black box) for patch
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_handle_patch
  bbtest_success = 1;
NumErrors = 0;
try
  x = [ 0 1 0 1]';
catch
  NumErrors = NumErrors + 1;
end
try
  y = [ 0 0 1 1]';
catch
  NumErrors = NumErrors + 1;
end
try
  c = [ 1 1 1 ];
catch
  NumErrors = NumErrors + 1;
end
try
  patch(x,y,c)
catch
  NumErrors = NumErrors + 1;
end
try
  axis equal
catch
  NumErrors = NumErrors + 1;
end
try
  view(3)
catch
  NumErrors = NumErrors + 1;
end
try
  mprint patch1
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
