% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_dec2bin
  bbtest_success = 1;
NumErrors = 0;
try
  dec2bin(56)

catch
  NumErrors = NumErrors + 1;
end
try
  dec2bin(1039456)

catch
  NumErrors = NumErrors + 1;
end
try
  dec2bin([63,73,32],5)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
