% Regression test function (black box) for isa
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_inspection_isa
  bbtest_success = 1;
NumErrors = 0;
try
  a = {1}
catch
  NumErrors = NumErrors + 1;
end
try
  isa(a,'char')
catch
  NumErrors = NumErrors + 1;
end
try
  isa(a,'cell')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  a = 'hello'
catch
  NumErrors = NumErrors + 1;
end
try
  isa(a,'char') && strcmp(a,'hello')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
