% Regression test function (black box) for randmulti
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_random_randmulti
  bbtest_success = 1;
NumErrors = 0;
try
  randmulti(10000,[0.4999,0.4999,0.0002])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
