% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_zlabel
  bbtest_success = 1;
NumErrors = 0;
try
  t = linspace(0,5*pi);

catch
  NumErrors = NumErrors + 1;
end
try
  x = cos(t);

catch
  NumErrors = NumErrors + 1;
end
try
  y = sin(t);

catch
  NumErrors = NumErrors + 1;
end
try
  z = t;

catch
  NumErrors = NumErrors + 1;
end
try
  plot3(x,y,z,'r-');

catch
  NumErrors = NumErrors + 1;
end
try
  view(3);

catch
  NumErrors = NumErrors + 1;
end
try
  zlabel('time');

catch
  NumErrors = NumErrors + 1;
end
try
  mprint zlabel1

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
