% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_continue
  bbtest_success = 1;
NumErrors = 0;
try
  continue_ex

catch
  NumErrors = NumErrors + 1;
end
try
  sum([1:4,6:10])

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
