% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_acsc
  bbtest_success = 1;
NumErrors = 0;
try
  x1 = -10:.01:-1.01;

catch
  NumErrors = NumErrors + 1;
end
try
  x2 = 1.01:.01:10;

catch
  NumErrors = NumErrors + 1;
end
try
  plot(x1,acsc(x1),x2,acsc(x2)); grid('on');

catch
  NumErrors = NumErrors + 1;
end
try
  mprint('acscplot');

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
