% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_acosh
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(1,pi);

catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,acosh(x)); grid('on');

catch
  NumErrors = NumErrors + 1;
end
try
  mprint('acoshplot');

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
