% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_xlabel
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(-1,1);

catch
  NumErrors = NumErrors + 1;
end
try
  y = cos(2*pi*x);

catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,y,'r-');

catch
  NumErrors = NumErrors + 1;
end
try
  xlabel('time');

catch
  NumErrors = NumErrors + 1;
end
try
  mprint xlabel1

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
