% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_num2hex
  bbtest_success = 1;
NumErrors = 0;
try
  num2hex([1 0 0.1 -pi inf nan])

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  num2hex(float([1 0 0.1 -pi inf nan]))

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
