% Regression test function (black box) for setprintlimit
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_io_setprintlimit
  bbtest_success = 1;
NumErrors = 0;
try
  A = randn(512);
catch
  NumErrors = NumErrors + 1;
end
try
  setprintlimit(10)
catch
  NumErrors = NumErrors + 1;
end
try
  A
catch
  NumErrors = NumErrors + 1;
end
try
  setprintlimit(1000)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
