% Regression test function (black box) for hold
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_handle_hold
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(-5,5,500);
catch
  NumErrors = NumErrors + 1;
end
try
  t = exp(-x.^2);
catch
  NumErrors = NumErrors + 1;
end
try
  y = t.*cos(2*pi*x*3);
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,y);
catch
  NumErrors = NumErrors + 1;
end
try
  mprint hold1
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  plot(x,y);
catch
  NumErrors = NumErrors + 1;
end
try
  hold on
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,t,'g-',x,-t,'b-')
catch
  NumErrors = NumErrors + 1;
end
try
  mprint hold2
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
