% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_threadid
  bbtest_success = 1;
NumErrors = 0;
try
  threadid

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  t_id = threadnew

catch
  NumErrors = NumErrors + 1;
end
try
  id = threadcall(t_id,1000,'threadid')

catch
  NumErrors = NumErrors + 1;
end
try
  threadfree(t_id);

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
