% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_erf
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(-5,5);

catch
  NumErrors = NumErrors + 1;
end
try
  y = erf(x);

catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,y); xlabel('x'); ylabel('erf(x)');

catch
  NumErrors = NumErrors + 1;
end
try
  mprint erf1

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
