% Regression test function (black box) for exist
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_inspection_exist
  bbtest_success = 1;
NumErrors = 0;
try
  a = randn(3,5,2)
catch
  NumErrors = NumErrors + 1;
end
try
  b = []
catch
  NumErrors = NumErrors + 1;
end
try
  who
catch
  NumErrors = NumErrors + 1;
end
try
  exist('a')
catch
  NumErrors = NumErrors + 1;
end
try
  exist('b')
catch
  NumErrors = NumErrors + 1;
end
try
  exist('c')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
