% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_randnchi
  bbtest_success = 1;
NumErrors = 0;
try
  randnchi(5*ones(1,9),0.3)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
