% Regression test function (black box) for title
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_handle_title
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(-1,1);
catch
  NumErrors = NumErrors + 1;
end
try
  y = cos(2*pi*x);
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,y,'r-');
catch
  NumErrors = NumErrors + 1;
end
try
  title('cost over time');
catch
  NumErrors = NumErrors + 1;
end
try
  mprint title1
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  title('cost over time','fontsize',20);
catch
  NumErrors = NumErrors + 1;
end
try
  mprint title2
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
