% Regression test function (black box) for poly
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_curvefit_poly
  bbtest_success = 1;
NumErrors = 0;
try
  A = [1,2,3;4,5,6;7,8,0]
catch
  NumErrors = NumErrors + 1;
end
try
  p = poly(A)
catch
  NumErrors = NumErrors + 1;
end
try
  r = roots(p)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
