% Regression test function (black box) for script
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_functions_script
  bbtest_success = 1;
NumErrors = 0;
try
  tscript
catch
  NumErrors = NumErrors + 1;
end
try
  who
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
