% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_nargout
  bbtest_success = 1;
NumErrors = 0;
try
  a1 = nargouttest

catch
  NumErrors = NumErrors + 1;
end
try
  [a1,a2] = nargouttest

catch
  NumErrors = NumErrors + 1;
end
try
  [a1,a2,a3] = nargouttest

catch
  NumErrors = NumErrors + 1;
end
try
  [a1,a2,a3,a4,a5] = nargouttest

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
