% Regression test function (black box) for acsc
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_acsc
  bbtest_success = 1;
NumErrors = 0;
try
  x1 = -10:.01:-1.01;
catch
  NumErrors = NumErrors + 1;
end
try
  x2 = 1.01:.01:10;
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x1,acsc(x1),x2,acsc(x2)); grid('on');
catch
  NumErrors = NumErrors + 1;
end
try
  mprint('acscplot');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
