% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_int2bin
  bbtest_success = 1;
NumErrors = 0;
try
  A = [2;5;6;2]

catch
  NumErrors = NumErrors + 1;
end
try
  int2bin(A,8)

catch
  NumErrors = NumErrors + 1;
end
try
  A = [1;2;-5;2]

catch
  NumErrors = NumErrors + 1;
end
try
  int2bin(A,8)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
