% Regression test function (black box) for acosh
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_acosh
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(1,pi);
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,acosh(x)); grid('on');
catch
  NumErrors = NumErrors + 1;
end
try
  mprint('acoshplot');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
