% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_tubeplot
  bbtest_success = 1;
NumErrors = 0;
try
  t=0:(2*pi/100):(2*pi);

catch
  NumErrors = NumErrors + 1;
end
try
  x=cos(t*2).*(2+sin(t*3)*.3);

catch
  NumErrors = NumErrors + 1;
end
try
  y=sin(t*2).*(2+sin(t*3)*.3);

catch
  NumErrors = NumErrors + 1;
end
try
  z=cos(t*3)*.3;

catch
  NumErrors = NumErrors + 1;
end
try
  tubeplot(x,y,z,0.14*sin(t*5)+.29,t,10);

catch
  NumErrors = NumErrors + 1;
end
try
  mprint tubeplot1

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
