% Regression test function (black box) for error
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_flow_error
  bbtest_success = 1;
NumErrors = 0;
try
  evenoddtest(4)
catch
  NumErrors = NumErrors + 1;
end
try
  evenoddtest(5)
catch
  NumErrors = NumErrors + 1;
end
try
  evenoddtest(0)
catch
  NumErrors = NumErrors + 1;
end
try
  evenoddtest(pi)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 2) bbtest_success = 0; return; end
