% Regression test function (black box) for contour
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_handle_contour
  bbtest_success = 1;
NumErrors = 0;
try
  [x,y] = meshgrid(linspace(-1,1,25),linspace(-2,2,30));
catch
  NumErrors = NumErrors + 1;
end
try
  z = x.*exp(-x.^2-y.^2);
catch
  NumErrors = NumErrors + 1;
end
try
  contour(z)
catch
  NumErrors = NumErrors + 1;
end
try
  mprint contour1
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  contour(x,y,z)
catch
  NumErrors = NumErrors + 1;
end
try
  mprint contour2
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  contour(x,y,z,[-.4,0.,3])
catch
  NumErrors = NumErrors + 1;
end
try
  mprint contour3
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  contour(x,y,z,'b-')
catch
  NumErrors = NumErrors + 1;
end
try
  mprint contour4
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
