% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_ipermute
  bbtest_success = 1;
NumErrors = 0;
try
  A = randn(13,5,7,2);

catch
  NumErrors = NumErrors + 1;
end
try
  size(A)

catch
  NumErrors = NumErrors + 1;
end
try
  B = permute(A,[3,4,2,1]);

catch
  NumErrors = NumErrors + 1;
end
try
  size(B)

catch
  NumErrors = NumErrors + 1;
end
try
  C = ipermute(B,[3,4,2,1]);

catch
  NumErrors = NumErrors + 1;
end
try
  size(C)

catch
  NumErrors = NumErrors + 1;
end
try
  any(A~=C)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
