% Regression test function (black box) for zoom
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_handle_zoom
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(-1,1,300)'*ones(1,600);
catch
  NumErrors = NumErrors + 1;
end
try
  y = ones(300,1)*linspace(-1,1,600);
catch
  NumErrors = NumErrors + 1;
end
try
  Z = exp(-(x.^2+y.^2)/0.3);
catch
  NumErrors = NumErrors + 1;
end
try
  image(Z);
catch
  NumErrors = NumErrors + 1;
end
try
  zoom(1.0);
catch
  NumErrors = NumErrors + 1;
end
try
  mprint zoom1
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  image(Z);
catch
  NumErrors = NumErrors + 1;
end
try
  zoom(0.6);
catch
  NumErrors = NumErrors + 1;
end
try
  mprint zoom3
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  image(Z)
catch
  NumErrors = NumErrors + 1;
end
try
  zoom(1.3);
catch
  NumErrors = NumErrors + 1;
end
try
  mprint zoom4
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  image(Z);
catch
  NumErrors = NumErrors + 1;
end
try
  zoom(0);
catch
  NumErrors = NumErrors + 1;
end
try
  sizefig(200,400);
catch
  NumErrors = NumErrors + 1;
end
try
  mprint zoom5
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  image(Z);
catch
  NumErrors = NumErrors + 1;
end
try
  zoom(-1);
catch
  NumErrors = NumErrors + 1;
end
try
  sizefig(200,400);
catch
  NumErrors = NumErrors + 1;
end
try
  mprint zoom6
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
