% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_feval
  bbtest_success = 1;
NumErrors = 0;
try
  feval('cos',pi/4)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  c = @cos

catch
  NumErrors = NumErrors + 1;
end
try
  feval(c,pi/4)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  afunc = inline('cos(t)+sin(t)','t')

catch
  NumErrors = NumErrors + 1;
end
try
  feval(afunc,pi)

catch
  NumErrors = NumErrors + 1;
end
try
  afunc(pi)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
