% Regression test function (black box) for isalpha
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_string_isalpha
  bbtest_success = 1;
NumErrors = 0;
try
  isalpha('numb3r5')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
