% Regression test function (black box) for verstring
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_freemat_verstring
  bbtest_success = 1;
NumErrors = 0;
try
  verstring
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
