% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_rightdivide
  bbtest_success = 1;
NumErrors = 0;
try
  B = [1,1;0,1];

catch
  NumErrors = NumErrors + 1;
end
try
  A = [4,5]

catch
  NumErrors = NumErrors + 1;
end
try
  A/B

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
