% Regression test function (black box) for toc
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_freemat_toc
  bbtest_success = 1;
NumErrors = 0;
try
  A = rand(100);
catch
  NumErrors = NumErrors + 1;
end
try
  b = rand(100,1);
catch
  NumErrors = NumErrors + 1;
end
try
  tic; c = A\b; toc
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
