% Regression test function (black box) for roots
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_curvefit_roots
  bbtest_success = 1;
NumErrors = 0;
try
  roots([1 -6 -72 -27])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
