% Regression test function (black box) for pi
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_constants_pi
  bbtest_success = 1;
NumErrors = 0;
try
  pi
catch
  NumErrors = NumErrors + 1;
end
try
  cos(pi)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
