% Regression test function (black box) for teps
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_constants_teps
  bbtest_success = 1;
NumErrors = 0;
try
  teps(float(3.4))
catch
  NumErrors = NumErrors + 1;
end
try
  teps(complex(3.4+i*2))
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
