% Regression test function (black box) for plot3
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_handle_plot3
  bbtest_success = 1;
NumErrors = 0;
try
  t = linspace(0,5*pi,200);
catch
  NumErrors = NumErrors + 1;
end
try
  x = cos(t); y = sin(t); z = t;
catch
  NumErrors = NumErrors + 1;
end
try
  plot3(x,y,z);
catch
  NumErrors = NumErrors + 1;
end
try
  view(3);
catch
  NumErrors = NumErrors + 1;
end
try
  mprint plt3
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
