% Regression test function (black box) for etime
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_freemat_etime
  bbtest_success = 1;
NumErrors = 0;
try
  x1 = clock;
catch
  NumErrors = NumErrors + 1;
end
try
  sleep(1);
catch
  NumErrors = NumErrors + 1;
end
try
  x2 = clock;
catch
  NumErrors = NumErrors + 1;
end
try
  etime(x2,x1);
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
