% Regression test function (black box) for sub2ind
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_elementary_sub2ind
  bbtest_success = 1;
NumErrors = 0;
try
  A = randi(ones(3,4),10*ones(3,4))
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  n = sub2ind(size(A),1:3,2:4)
catch
  NumErrors = NumErrors + 1;
end
try
  A(n)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
