% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_bitxor
  bbtest_success = 1;
NumErrors = 0;
try
  bitand(uint16([1,16,255]),uint16([3,17,128]))

catch
  NumErrors = NumErrors + 1;
end
try
  bitand(uint16([1,16,255]),uint16(3))

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
