% Regression test function (black box) for switch
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_flow_switch
  bbtest_success = 1;
NumErrors = 0;
try
  switch_test('root beer')
catch
  NumErrors = NumErrors + 1;
end
try
  switch_test('red')
catch
  NumErrors = NumErrors + 1;
end
try
  switch_test('carpet')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
