% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_imwrite
  bbtest_success = 1;
NumErrors = 0;
try
  a =  uint8(255*rand(64));

catch
  NumErrors = NumErrors + 1;
end
try
  figure(1), image(a), colormap(gray)

catch
  NumErrors = NumErrors + 1;
end
try
  title('image to save')

catch
  NumErrors = NumErrors + 1;
end
try
  imwrite(a, 'test.bmp')

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  b = imread('test.bmp');

catch
  NumErrors = NumErrors + 1;
end
try
  figure(2), image(b), colormap(gray)

catch
  NumErrors = NumErrors + 1;
end
try
  title('loaded image')

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
