% Regression test function (black box) for ode45
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_num_ode45
  bbtest_success = 1;
NumErrors = 0;
try
        [t,y]=ode45(@(t,y) y,[0 3],1)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
        SOL=ode45(@(t,y) y,[0 3],1)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
