% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_clim
  bbtest_success = 1;
NumErrors = 0;
try
  x = repmat(linspace(-1,1),[100,1]); y = x';

catch
  NumErrors = NumErrors + 1;
end
try
  z = exp(-x.^2-y.^2);

catch
  NumErrors = NumErrors + 1;
end
try
  image(z);

catch
  NumErrors = NumErrors + 1;
end
try
  min(z(:))

catch
  NumErrors = NumErrors + 1;
end
try
  max(z(:))

catch
  NumErrors = NumErrors + 1;
end
try
  mprint clim1

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  image(z);

catch
  NumErrors = NumErrors + 1;
end
try
  clim([0,0.2]);

catch
  NumErrors = NumErrors + 1;
end
try
  mprint clim2

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
