% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_hold
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(-5,5,500);

catch
  NumErrors = NumErrors + 1;
end
try
  t = exp(-x.^2);

catch
  NumErrors = NumErrors + 1;
end
try
  y = t.*cos(2*pi*x*3);

catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,y);

catch
  NumErrors = NumErrors + 1;
end
try
  mprint hold1

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  plot(x,y);

catch
  NumErrors = NumErrors + 1;
end
try
  hold on

catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,t,'g-',x,-t,'b-')

catch
  NumErrors = NumErrors + 1;
end
try
  mprint hold2

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
