% Regression test function (black box) for unique
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_array_unique
  bbtest_success = 1;
NumErrors = 0;
try
  A = randi(1,3*ones(15,3))
catch
  NumErrors = NumErrors + 1;
end
try
  unique(A,'rows')
catch
  NumErrors = NumErrors + 1;
end
try
  [b,m,n] = unique(A,'rows');
catch
  NumErrors = NumErrors + 1;
end
try
  b
catch
  NumErrors = NumErrors + 1;
end
try
  A(m,:)
catch
  NumErrors = NumErrors + 1;
end
try
  b(n,:)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  A = randi(1,5*ones(10,1))
catch
  NumErrors = NumErrors + 1;
end
try
  unique(A)
catch
  NumErrors = NumErrors + 1;
end
try
  [b,m,n] = unique(A,'rows');
catch
  NumErrors = NumErrors + 1;
end
try
  b
catch
  NumErrors = NumErrors + 1;
end
try
  A(m)
catch
  NumErrors = NumErrors + 1;
end
try
  b(n)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  A = {'hi','bye','good','tell','hi','bye'}
catch
  NumErrors = NumErrors + 1;
end
try
  unique(A)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
