% Regression test function (black box) for logicalops
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_operators_logicalops
  bbtest_success = 1;
NumErrors = 0;
try
  a = (randn(1,6)>0)
catch
  NumErrors = NumErrors + 1;
end
try
  b = (randn(1,6)>0)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  c = a | b
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  d = a & b
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  xor = c & (~d)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  c(d) = 0
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
