% Regression test function (black box) for contour3
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_handle_contour3
  bbtest_success = 1;
NumErrors = 0;
try
  [x,y] = meshgrid([-2:.25:2]);
catch
  NumErrors = NumErrors + 1;
end
try
  z=x.*exp(-x.^2-y.^2);
catch
  NumErrors = NumErrors + 1;
end
try
  contour3(x,y,z,30);
catch
  NumErrors = NumErrors + 1;
end
try
  axis square;
catch
  NumErrors = NumErrors + 1;
end
try
  view(-15,25)
catch
  NumErrors = NumErrors + 1;
end
try
  mprint contour3_1
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
