% Regression test function (black box) for eye
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_array_eye
  bbtest_success = 1;
NumErrors = 0;
try
  eye(3)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
