% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_semilogx
  bbtest_success = 1;
NumErrors = 0;
try
  y = linspace(0,2);

catch
  NumErrors = NumErrors + 1;
end
try
  x = (10).^y;

catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,y,'r-');

catch
  NumErrors = NumErrors + 1;
end
try
  mprint semilogx1

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  semilogx(x,y,'r-');

catch
  NumErrors = NumErrors + 1;
end
try
  mprint semilogx2

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
