% Regression test function (black box) for cell
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_variables_cell
  bbtest_success = 1;
NumErrors = 0;
try
  A = {14,'hello',[1:10]}
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  B = {pi,i;e,-1}
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  C = {A,B}
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
