% Regression test function (black box) for bitxor
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_binary_bitxor
  bbtest_success = 1;
NumErrors = 0;
try
  bitand(uint16([1,16,255]),uint16([3,17,128]))
catch
  NumErrors = NumErrors + 1;
end
try
  bitand(uint16([1,16,255]),uint16(3))
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
