% Regression test function (black box) for fwrite
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_io_fwrite
  bbtest_success = 1;
NumErrors = 0;
try
  A = float(randn(512));
catch
  NumErrors = NumErrors + 1;
end
try
  fp = fopen('test.dat','w');
catch
  NumErrors = NumErrors + 1;
end
try
  fwrite(fp,A,'single');
catch
  NumErrors = NumErrors + 1;
end
try
  fclose(fp);
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
