% Regression test function (black box) for erf
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_erf
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(-5,5);
catch
  NumErrors = NumErrors + 1;
end
try
  y = erf(x);
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,y); xlabel('x'); ylabel('erf(x)');
catch
  NumErrors = NumErrors + 1;
end
try
  mprint erf1
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
