% Regression test function (black box) for hex2dec
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_elementary_hex2dec
  bbtest_success = 1;
NumErrors = 0;
try
  hex2dec('3ff')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  hex2dec(['0ff';'2de';'123'])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
