% Regression test function (black box) for polyder
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_curvefit_polyder
  bbtest_success = 1;
NumErrors = 0;
try
  polyder([2,3,4])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  polyder([2,3,4],7)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  [n,d] = polyder([2,3,4],5)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
