% Regression test function (black box) for threadcall
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_thread_threadcall
  bbtest_success = 1;
NumErrors = 0;
try
  id = threadnew
catch
  NumErrors = NumErrors + 1;
end
try
  d = threadcall(id,1000,'cos',1.02343)
catch
  NumErrors = NumErrors + 1;
end
try
  threadfree(id)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
