% Regression test function (black box) for strstr
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_string_strstr
  bbtest_success = 1;
NumErrors = 0;
try
  strstr('hello','lo')
catch
  NumErrors = NumErrors + 1;
end
try
  strstr('quick brown fox','own')
catch
  NumErrors = NumErrors + 1;
end
try
  strstr('free stuff','lunch')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
