% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_typeof
  bbtest_success = 1;
NumErrors = 0;
try
  typeof({1})

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  typeof(struct('foo',3))

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  typeof(3>5)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  typeof(uint8(3))

catch
  NumErrors = NumErrors + 1;
end
try
  typeof(int8(8))

catch
  NumErrors = NumErrors + 1;
end
try
  typeof(uint16(3))

catch
  NumErrors = NumErrors + 1;
end
try
  typeof(int16(8))

catch
  NumErrors = NumErrors + 1;
end
try
  typeof(uint32(3))

catch
  NumErrors = NumErrors + 1;
end
try
  typeof(int32(3))

catch
  NumErrors = NumErrors + 1;
end
try
  typeof(uint64(3))

catch
  NumErrors = NumErrors + 1;
end
try
  typeof(int64(3))

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  typeof(1.0f)

catch
  NumErrors = NumErrors + 1;
end
try
  typeof(1.0D)

catch
  NumErrors = NumErrors + 1;
end
try
  typeof(1.0f+i)

catch
  NumErrors = NumErrors + 1;
end
try
  typeof(1.0D+2.0D*i)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
