% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_numel
  bbtest_success = 1;
NumErrors = 0;
try
  x = rand(4,4,3);

catch
  NumErrors = NumErrors + 1;
end
try
  length(x)

catch
  NumErrors = NumErrors + 1;
end
try
  numel(x)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  numel(x,1:3,1:2,2)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
