% Regression test function (black box) for sqrt
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_sqrt
  bbtest_success = 1;
NumErrors = 0;
try
  sqrt(9)
catch
  NumErrors = NumErrors + 1;
end
try
  sqrt(i)
catch
  NumErrors = NumErrors + 1;
end
try
  sqrt(-1)
catch
  NumErrors = NumErrors + 1;
end
try
  x = rand(4)
catch
  NumErrors = NumErrors + 1;
end
try
  sqrt(x)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
