% Regression test function (black box) for break
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_flow_break
  bbtest_success = 1;
NumErrors = 0;
try
  break_ex
catch
  NumErrors = NumErrors + 1;
end
try
  sum(1:5)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
