% Regression test function (black box) for csvread
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_io_csvread
  bbtest_success = 1;
NumErrors = 0;
try
  csvread('sample_data.csv')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  csvread('sample_data.csv',1,2)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  csvread('sample_data.csv',1,2,[1,2,3,4])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
