% Regression test function (black box) for nonzeros
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_array_nonzeros
  bbtest_success = 1;
NumErrors = 0;
try
  a = rand(8); a(a>0.2) = 0;
catch
  NumErrors = NumErrors + 1;
end
try
  A = sparse(a)
catch
  NumErrors = NumErrors + 1;
end
try
  nonzeros(A)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
