% Regression test function (black box) for cosd
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_cosd
  bbtest_success = 1;
NumErrors = 0;
try
  cosd(45)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  cosd(60)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
