% Regression test function (black box) for keywords
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_functions_keywords
  bbtest_success = 1;
NumErrors = 0;
try
  keyfunc(1,3)                % specify a and b, defaults for the others
catch
  NumErrors = NumErrors + 1;
end
try
  keyfunc(1,3,/printit)       % specify printit is true
catch
  NumErrors = NumErrors + 1;
end
try
  keyfunc(/operation='-',2,3) % assigns a=2, b=3
catch
  NumErrors = NumErrors + 1;
end
try
  keyfunc(4,/operation='*',/printit) % error as b is unspecified
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 1) bbtest_success = 0; return; end
