% Regression test function (black box) for exp
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_exp
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(-1,1);
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,exp(x))
catch
  NumErrors = NumErrors + 1;
end
try
  mprint('expplot1');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  x = linspace(-1,1);
catch
  NumErrors = NumErrors + 1;
end
try
  plot(exp(-i*x*2*pi))
catch
  NumErrors = NumErrors + 1;
end
try
  mprint('expplot2');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
