% Regression test function (black box) for cast
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_typecast_cast
  bbtest_success = 1;
NumErrors = 0;
try
  cast(pi,'uint8')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  cast([1 0 3 0],'logical')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
