% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_times
  bbtest_success = 1;
NumErrors = 0;
try
  a = [1,3,4;0,2,1]

catch
  NumErrors = NumErrors + 1;
end
try
  b = a * 2

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  a = [1,2,0;4,2,3]

catch
  NumErrors = NumErrors + 1;
end
try
  b = [5;3;1]

catch
  NumErrors = NumErrors + 1;
end
try
  c = a*b

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
