% Regression test function (black box) for polyint
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_curvefit_polyint
  bbtest_success = 1;
NumErrors = 0;
try
  polyint([2,3,4])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  polyint([2,3,4],5)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
