% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_fgetline
  bbtest_success = 1;
NumErrors = 0;
try
  fp = fopen('testtext','w');

catch
  NumErrors = NumErrors + 1;
end
try
  fprintf(fp,'String 1\n');

catch
  NumErrors = NumErrors + 1;
end
try
  fprintf(fp,'String 2\n');

catch
  NumErrors = NumErrors + 1;
end
try
  fclose(fp);

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  fp = fopen('testtext','r')

catch
  NumErrors = NumErrors + 1;
end
try
  fgetline(fp)

catch
  NumErrors = NumErrors + 1;
end
try
  fgetline(fp)

catch
  NumErrors = NumErrors + 1;
end
try
  fclose(fp);

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
