% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_meshgrid
  bbtest_success = 1;
NumErrors = 0;
try
  [X,Y] = meshgrid(-2:.4:2)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  [X,Y] = meshgrid([1,2,3,4],[6,7,8])

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
