% Regression test function (black box) for inf
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_constants_inf
  bbtest_success = 1;
NumErrors = 0;
try
  inf*0
catch
  NumErrors = NumErrors + 1;
end
try
  inf*2
catch
  NumErrors = NumErrors + 1;
end
try
  inf*-2
catch
  NumErrors = NumErrors + 1;
end
try
  inf/inf
catch
  NumErrors = NumErrors + 1;
end
try
  inf/0
catch
  NumErrors = NumErrors + 1;
end
try
  inf/nan
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  uint32(inf)
catch
  NumErrors = NumErrors + 1;
end
try
  complex(inf)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
