% Regression test function (black box) for sind
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_sind
  bbtest_success = 1;
NumErrors = 0;
try
  sind(45)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  sind(30)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
