% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_cos
  bbtest_success = 1;
NumErrors = 0;
try
  x = linspace(0,1);

catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,cos(2*pi*x))

catch
  NumErrors = NumErrors + 1;
end
try
  mprint('cosplot');

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
