% Regression test function (black box) for logical
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_typecast_logical
  bbtest_success = 1;
NumErrors = 0;
try
  logical([1,2,3,0,0,0,5,2,2])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  logical([pi,pi,0,e,0,-1])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
