% Regression test function (black box) for randgamma
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_random_randgamma
  bbtest_success = 1;
NumErrors = 0;
try
  randgamma(1,15*ones(1,9))
catch
  NumErrors = NumErrors + 1;
end
try
  sum(randexp(ones(15,9)))
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
