% Regression test function (black box) for iscellstr
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_inspection_iscellstr
  bbtest_success = 1;
NumErrors = 0;
try
  A = {'Hello','Yellow';'Mellow','Othello'}
catch
  NumErrors = NumErrors + 1;
end
try
  iscellstr(A)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
