% Regression test function (black box) for special
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_functions_special
  bbtest_success = 1;
NumErrors = 0;
try
  strcattest('hi','ho')
catch
  NumErrors = NumErrors + 1;
end
try
  strcattest 'hi' 'ho'
catch
  NumErrors = NumErrors + 1;
end
try
  strcattest hi ho
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
