% Regression test function (black box) for floor
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_elementary_floor
  bbtest_success = 1;
NumErrors = 0;
try
  floor(3)
catch
  NumErrors = NumErrors + 1;
end
try
  floor(-3)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  floor(3.023)
catch
  NumErrors = NumErrors + 1;
end
try
  floor(-2.341)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
