% Regression test function (black box) for load
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_io_load
  bbtest_success = 1;
NumErrors = 0;
try
  D = {1,5,'hello'};
catch
  NumErrors = NumErrors + 1;
end
try
  s = 'test string';
catch
  NumErrors = NumErrors + 1;
end
try
  x = randn(512,1);
catch
  NumErrors = NumErrors + 1;
end
try
  z = zeros(512);
catch
  NumErrors = NumErrors + 1;
end
try
  who
catch
  NumErrors = NumErrors + 1;
end
try
  save loadsave.dat
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  clear D s x z
catch
  NumErrors = NumErrors + 1;
end
try
  who
catch
  NumErrors = NumErrors + 1;
end
try
  load loadsave.dat
catch
  NumErrors = NumErrors + 1;
end
try
  who
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
