% Regression test function (black box) for strrep
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_string_strrep
  bbtest_success = 1;
NumErrors = 0;
try
  strrep('Matlab is great','Matlab','FreeMat')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  strrep({'time is money';'A stitch in time';'No time for games'},'time','money')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
