% Regression test function (black box) for cd
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_os_cd
  bbtest_success = 1;
NumErrors = 0;
try
  pwd
catch
  NumErrors = NumErrors + 1;
end
try
  cd ..
catch
  NumErrors = NumErrors + 1;
end
try
  pwd
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  a = pwd;
catch
  NumErrors = NumErrors + 1;
end
try
  cd(a)
catch
  NumErrors = NumErrors + 1;
end
try
  pwd
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
