% Regression test function (black box) for bin2dec
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_typecast_bin2dec
  bbtest_success = 1;
NumErrors = 0;
try
  bin2dec('101110')
catch
  NumErrors = NumErrors + 1;
end
try
  bin2dec('010')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
