% Regression test function (black box) for i
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_constants_i
  bbtest_success = 1;
NumErrors = 0;
try
  i
catch
  NumErrors = NumErrors + 1;
end
try
  i^2
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  j
catch
  NumErrors = NumErrors + 1;
end
try
  j^2
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  accum = 0; for i=1:100; accum = accum + i; end; accum
catch
  NumErrors = NumErrors + 1;
end
try
  i
catch
  NumErrors = NumErrors + 1;
end
try
  clear i
catch
  NumErrors = NumErrors + 1;
end
try
  i
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
