% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_polyval
  bbtest_success = 1;
NumErrors = 0;
try
  p = [1 0 0 0]

catch
  NumErrors = NumErrors + 1;
end
try
  x = linspace(-1,1);

catch
  NumErrors = NumErrors + 1;
end
try
  y = polyval(p,x);

catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,y,'r-')

catch
  NumErrors = NumErrors + 1;
end
try
  mprint polyval1

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
