% Regression test function (black box) for randnbin
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_random_randnbin
  bbtest_success = 1;
NumErrors = 0;
try
  randnbin(3*ones(1,4),.01)
catch
  NumErrors = NumErrors + 1;
end
try
  randnbin(6*ones(1,4),.01)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
