% Regression test function (black box) for version
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_freemat_version
  bbtest_success = 1;
NumErrors = 0;
try
  version
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
