% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_circshift
  bbtest_success = 1;
NumErrors = 0;
try
  x = int32(rand(4,5)*10)

catch
  NumErrors = NumErrors + 1;
end
try
  circshift(x,[1,0])

catch
  NumErrors = NumErrors + 1;
end
try
  circshift(x,[0,-1])

catch
  NumErrors = NumErrors + 1;
end
try
  circshift(x,[2,2])

catch
  NumErrors = NumErrors + 1;
end
try
  x = int32(rand(4,5,3)*10)

catch
  NumErrors = NumErrors + 1;
end
try
  circshift(x,[1,0,0])

catch
  NumErrors = NumErrors + 1;
end
try
  circshift(x,[0,-1,0])

catch
  NumErrors = NumErrors + 1;
end
try
  circshift(x,[0,0,-1])

catch
  NumErrors = NumErrors + 1;
end
try
  circshift(x,[2,-3,1])

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
