% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_atan
  bbtest_success = 1;
NumErrors = 0;
try
  t = linspace(-1,1);

catch
  NumErrors = NumErrors + 1;
end
try
  plot(t,atan(t))

catch
  NumErrors = NumErrors + 1;
end
try
  mprint('atanplot');

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
