% Regression test function (black box) for func2str
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_functions_func2str
  bbtest_success = 1;
NumErrors = 0;
try
  y = @sin
catch
  NumErrors = NumErrors + 1;
end
try
  x = func2str(y)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  y = @(x) x.^2
catch
  NumErrors = NumErrors + 1;
end
try
  x = func2str(y)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
