% Regression test function (black box) for eigs
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_sparse_eigs
  bbtest_success = 1;
NumErrors = 0;
try
  a = sparse(rand(9));
catch
  NumErrors = NumErrors + 1;
end
try
  eigs(a)
catch
  NumErrors = NumErrors + 1;
end
try
  eig(full(a))
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  eigs(a,4,'sm')
catch
  NumErrors = NumErrors + 1;
end
try
  eigs(a,4,'lr')
catch
  NumErrors = NumErrors + 1;
end
try
  eigs(a,4,'sr')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
