% Regression test function (black box) for asinh
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_asinh
  bbtest_success = 1;
NumErrors = 0;
try
  x = -5:.01:5;
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x,asinh(x)); grid('on');
catch
  NumErrors = NumErrors + 1;
end
try
  mprint('asinhplot');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
