% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_ode45
  bbtest_success = 1;
NumErrors = 0;
try
        [t,y]=ode45(@(t,y) y,[0 3],1)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
        SOL=ode45(@(t,y) y,[0 3],1)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
