% Regression test function (black box) for blanks
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_string_blanks
  bbtest_success = 1;
NumErrors = 0;
try
  sprintf(['x0123456789y\n','x',blanks(10),'y\n'])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
