% Regression test function (black box) for getenv
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_os_getenv
  bbtest_success = 1;
NumErrors = 0;
try
  getenv('HOME')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
