% Regression test function (black box) for printf
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_io_printf
  bbtest_success = 1;
NumErrors = 0;
try
  printf('intvalue is %d, floatvalue is %f\n',3,1.53);
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  printf('string value is %s\n','hello');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  printf('integer padded is %012d\n',32);
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  printf('float value is %+018.12f\n',pi);
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
