% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_idiv
  bbtest_success = 1;
NumErrors = 0;
try
  idiv(27,6)

catch
  NumErrors = NumErrors + 1;
end
try
  idiv(4,-2)

catch
  NumErrors = NumErrors + 1;
end
try
  idiv(15,3)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
