% Regression test function (black box) for conj
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_elementary_conj
  bbtest_success = 1;
NumErrors = 0;
try
  conj(3+4*i)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  conj([2,3,4])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  conj([2.0+3.0*i,i])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
