% Regression test function (black box) for if
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_flow_if
  bbtest_success = 1;
NumErrors = 0;
try
  if_test(1)
catch
  NumErrors = NumErrors + 1;
end
try
  if_test(2)
catch
  NumErrors = NumErrors + 1;
end
try
  if_test(3)
catch
  NumErrors = NumErrors + 1;
end
try
  if_test(pi)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
