% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_randi
  bbtest_success = 1;
NumErrors = 0;
try
  randi(zeros(1,6),5*ones(1,6))

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
