% Regression test function (black box) for winlev
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_handle_winlev
  bbtest_success = 1;
NumErrors = 0;
try
  t = linspace(-1,1,256);
catch
  NumErrors = NumErrors + 1;
end
try
  xmat = ones(256,1)*t; ymat = xmat';
catch
  NumErrors = NumErrors + 1;
end
try
  A = exp(-(xmat.^2 + ymat.^2)*100);
catch
  NumErrors = NumErrors + 1;
end
try
  image(A);
catch
  NumErrors = NumErrors + 1;
end
try
  mprint('winlev1');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  min(A(:))
catch
  NumErrors = NumErrors + 1;
end
try
  max(A(:))
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  image(A);
catch
  NumErrors = NumErrors + 1;
end
try
  winlev(1e-4,0.5e-4)
catch
  NumErrors = NumErrors + 1;
end
try
  mprint('winlev2');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  image(A);
catch
  NumErrors = NumErrors + 1;
end
try
  winlev(1e-4,0.5e-4)
catch
  NumErrors = NumErrors + 1;
end
try
  winlev
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
