% Regression test function (black box) for str2func
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_functions_str2func
  bbtest_success = 1;
NumErrors = 0;
try
  sin(.5)              % Calling the function directly
catch
  NumErrors = NumErrors + 1;
end
try
  y = str2func('sin')  % Convert it into a function handle
catch
  NumErrors = NumErrors + 1;
end
try
  y(.5)                % Calling 'sin' via the function handle
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  y = str2func('@(x) x.^2')
catch
  NumErrors = NumErrors + 1;
end
try
  y(2)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
