% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_angle
  bbtest_success = 1;
NumErrors = 0;
try
  x = 3+4*i

catch
  NumErrors = NumErrors + 1;
end
try
  a = abs(x)

catch
  NumErrors = NumErrors + 1;
end
try
  t = angle(x)

catch
  NumErrors = NumErrors + 1;
end
try
  a*exp(i*t)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
