% Regression test function (black box) for asech
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_asech
  bbtest_success = 1;
NumErrors = 0;
try
  x1 = -20:.01:-1;
catch
  NumErrors = NumErrors + 1;
end
try
  x2 = 1:.01:20;
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x1,imag(asech(x1)),x2,imag(asech(x2))); grid('on');
catch
  NumErrors = NumErrors + 1;
end
try
  mprint('asechplot');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
