% Regression test function (black box) for tan
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_tan
  bbtest_success = 1;
NumErrors = 0;
try
  t = linspace(-1,1);
catch
  NumErrors = NumErrors + 1;
end
try
  plot(t,tan(t))
catch
  NumErrors = NumErrors + 1;
end
try
  mprint('tanplot');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
