% Regression test function (black box) for zeros
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_array_zeros
  bbtest_success = 1;
NumErrors = 0;
try
  zeros(2,3,2)
catch
  NumErrors = NumErrors + 1;
end
try
  zeros(1,3)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  zeros([2,6])
catch
  NumErrors = NumErrors + 1;
end
try
  zeros([1,3])
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  uint16(zeros(3))
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  zeros(3,'int16')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
