% Regression test function (black box) for randnchi
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_random_randnchi
  bbtest_success = 1;
NumErrors = 0;
try
  randnchi(5*ones(1,9),0.3)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
