% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_tic
  bbtest_success = 1;
NumErrors = 0;
try
  A = rand(100);

catch
  NumErrors = NumErrors + 1;
end
try
  b = rand(100,1);

catch
  NumErrors = NumErrors + 1;
end
try
  tic; c = A\b; toc

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
