% Regression test function (black box) for feps
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_constants_feps
  bbtest_success = 1;
NumErrors = 0;
try
  feps
catch
  NumErrors = NumErrors + 1;
end
try
  1.0f+eps
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
