% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_string
  bbtest_success = 1;
NumErrors = 0;
try
  a = [104,101,108,108,111]

catch
  NumErrors = NumErrors + 1;
end
try
  string(a)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
