% Regression test function (black box) for deg2rad
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_deg2rad
  bbtest_success = 1;
NumErrors = 0;
try
  deg2rad(360) - 2*pi
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
