% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_plot3
  bbtest_success = 1;
NumErrors = 0;
try
  t = linspace(0,5*pi,200);

catch
  NumErrors = NumErrors + 1;
end
try
  x = cos(t); y = sin(t); z = t;

catch
  NumErrors = NumErrors + 1;
end
try
  plot3(x,y,z);

catch
  NumErrors = NumErrors + 1;
end
try
  view(3);

catch
  NumErrors = NumErrors + 1;
end
try
  mprint plt3

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
