% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_speye
  bbtest_success = 1;
NumErrors = 0;
try
  I = speye(5000);

catch
  NumErrors = NumErrors + 1;
end
try
  which I

catch
  NumErrors = NumErrors + 1;
end
try
  full(I(1:10,1:10))

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
