% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_ceil
  bbtest_success = 1;
NumErrors = 0;
try
  ceil(3)

catch
  NumErrors = NumErrors + 1;
end
try
  ceil(-3)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  ceil(float(3.023))

catch
  NumErrors = NumErrors + 1;
end
try
  ceil(float(-2.341))

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  ceil(4.312)

catch
  NumErrors = NumErrors + 1;
end
try
  ceil(-5.32)

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
