% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_text
  bbtest_success = 1;
NumErrors = 0;
try
  plot(rand(1,4))

catch
  NumErrors = NumErrors + 1;
end
try
  text([2,3],[0.5,0.5],{'hello','there'})

catch
  NumErrors = NumErrors + 1;
end
try
  mprint text1

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  plot(rand(1,4))

catch
  NumErrors = NumErrors + 1;
end
try
  text([2,3],[0.5,0.5],{'hello','there'},'fontsize',20)

catch
  NumErrors = NumErrors + 1;
end
try
  mprint text2

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
