% Regression test function (black box) for isfield
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_inspection_isfield
  bbtest_success = 1;
NumErrors = 0;
try
  a.foo = 32
catch
  NumErrors = NumErrors + 1;
end
try
  a.goo = 64
catch
  NumErrors = NumErrors + 1;
end
try
  isfield(a,'goo')
catch
  NumErrors = NumErrors + 1;
end
try
  isfield(a,'got')
catch
  NumErrors = NumErrors + 1;
end
try
  isfield(pi,'round')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
