% Regression test function (black box) for acsch
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_mathfunctions_acsch
  bbtest_success = 1;
NumErrors = 0;
try
  x1 = -20:.01:-1;
catch
  NumErrors = NumErrors + 1;
end
try
  x2 = 1:.01:20;
catch
  NumErrors = NumErrors + 1;
end
try
  plot(x1,acsch(x1),x2,acsch(x2)); grid('on');
catch
  NumErrors = NumErrors + 1;
end
try
  mprint('acschplot');
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
