% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_repmat
  bbtest_success = 1;
NumErrors = 0;
try
  x = [1 2 3 4]

catch
  NumErrors = NumErrors + 1;
end
try
  y = repmat(x,[5,1])

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  x = [1 2;3 4]

catch
  NumErrors = NumErrors + 1;
end
try
  y = repmat(x,[1,1,3])

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
