% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_bin2dec
  bbtest_success = 1;
NumErrors = 0;
try
  bin2dec('101110')

catch
  NumErrors = NumErrors + 1;
end
try
  bin2dec('010')

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
