% Regression test function (black blox) for FreeMat v4.0
% This function is autogenerated by helpgen.
function bbtest_success = bbtest_feps
  bbtest_success = 1;
NumErrors = 0;
try
  feps

catch
  NumErrors = NumErrors + 1;
end
try
  1.0f+eps

catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
