% Regression test function (black box) for svd
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_transforms_svd
  bbtest_success = 1;
NumErrors = 0;
try
  A = float(randn(2,3))
catch
  NumErrors = NumErrors + 1;
end
try
  [U,S,V] = svd(A)
catch
  NumErrors = NumErrors + 1;
end
try
  U*S*V'
catch
  NumErrors = NumErrors + 1;
end
try
  svd(A)
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
