% Regression test function (black box) for lower
% This function is autogenerated by helpgen.py
function bbtest_success = bbtest_string_lower
  bbtest_success = 1;
NumErrors = 0;
try
  lower('this Is Strange CAPitalizaTion')
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
NumErrors = 0;
try
  lower({'This','Is','Strange','CAPitalizaTion'})
catch
  NumErrors = NumErrors + 1;
end
if (NumErrors ~= 0) bbtest_success = 0; return; end
