/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define FLEX_DEBUG
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;

#define FLEX_DEBUG
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
static yyconst short int yy_accept[177] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   61,    5,
        3,    2,    5,    1,    4,   53,   53,   60,   52,   50,
       53,   51,   59,   58,   57,   35,   27,   57,   37,   38,
       28,   31,   26,   57,   56,   25,   57,   57,   57,   47,
       30,   33,   29,   32,   57,    7,    7,    8,    9,   14,
       60,   60,   60,   60,   60,   10,   13,   60,   60,   46,
       39,   60,   31,   56,   47,    3,    2,    1,    0,    0,
        0,   49,   27,   37,   23,   16,    0,   17,   55,   18,
       22,   55,   56,   55,   55,   54,   24,   19,   15,   20,

       47,   21,    0,    0,    8,    9,   14,    0,   11,   10,
       10,   10,   10,   12,   10,   10,   46,   45,   43,   44,
       40,   42,   41,    0,    0,   49,    0,   55,   55,   54,
       55,   55,   55,   54,    0,   55,   55,   54,    0,    0,
        0,    0,    0,    0,    0,   10,   10,   10,   10,    0,
        0,   48,    0,    0,   36,    0,    0,   55,    0,   55,
        0,    0,    0,    0,    0,    6,    0,    0,    0,    0,
       34,    0,    0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    6,    1,    1,    7,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,    1,    1,   22,   22,   22,   23,   24,   25,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       26,   27,   28,   29,   30,    1,   22,   31,   22,   32,

       33,   34,   22,   22,   22,   22,   22,   22,   22,   35,
       22,   22,   22,   36,   22,   37,   22,   22,   22,   22,
       22,   22,   38,    1,   39,   40,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[41] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    5,    6,    1,
        7,    6,    1,    8,    9,   10,   11,   12,    1,   13,
        1,   14,   14,   14,   14,    1,    5,    1,    7,   15,
       14,   14,   14,   14,   14,   14,   14,    1,    1,   16
    } ;

static yyconst short int yy_base[216] =
    {   0,
        0,    6,    8,   13,   19,   23,   51,    0,   89,  124,
      140,  156,  193,    0,   90,   91,  224,    0,  240,  941,
      237,  941,  235,    0,  941,  941,   18,  941,  941,  941,
      220,  941,  941,  941,  941,  941,  941,  183,    0,  941,
      941,  941,  941,  254,  269,  182,  164,  163,  162,    0,
      941,  941,  941,  941,  150,  941,  167,    0,  166,  941,
      163,  142,    0,    0,    0,    0,  141,    0,    0,    0,
      941,    1,  140,  139,  137,  133,  941,    0,   24,  118,
      116,    0,  941,    0,  941,  941,  100,  941,  287,  941,
      941,  305,    0,  941,  328,  941,  941,  941,  941,  941,

        0,  941,  361,  108,    0,  106,  941,   94,  941,    0,
        0,    0,    0,  941,    0,    0,    0,  941,  941,  941,
      941,  941,  941,   28,   42,    0,   98,  941,  390,  941,
        0,  941,  413,  941,   80,  111,  941,  941,   88,    0,
        0,    0,  135,    0,    0,    0,    0,    0,    0,    0,
      102,  941,   92,  127,  941,   47,   32,  219,   24,  220,
       26,  149,  261,  270,  295,  941,    9,    1,  313,  330,
      941,  341,  347,  352,  369,  941,  447,  463,  479,  495,
      511,  527,  543,   34,  559,  565,  579,  584,  599,   95,
      615,  623,  637,  645,  659,  675,  691,  697,  711,  727,

      743,  759,  775,  791,  105,  807,  815,  829,  837,  851,
      862,  876,  892,  908,  924
    } ;

static yyconst short int yy_def[216] =
    {   0,
      177,  177,  178,  178,  179,  179,  176,    7,  180,  180,
      181,  181,  176,   13,  182,  182,    7,   17,  176,  176,
      176,  176,  176,  183,  176,  176,  176,  176,  176,  176,
      184,  176,  176,  176,  176,  176,  176,  176,  185,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  186,
      176,  176,  176,  176,  176,  176,  187,  188,  176,  176,
      176,  189,  190,  191,  192,  193,  176,  194,  195,  196,
      176,  197,  176,   45,  186,  176,  176,  183,  176,  176,
      176,  198,  176,  185,  176,  176,  176,  176,  176,  176,
      176,  176,   45,  176,  176,  176,  176,  176,  176,  176,

      186,  176,  199,  187,  188,  176,  176,  189,  176,  193,
      200,  201,  193,  176,  202,  203,  196,  176,  176,  176,
      176,  176,  176,  176,  176,  198,  176,  176,  176,  176,
       92,  176,  176,  176,  176,  176,  176,  176,  204,  205,
      206,  207,  208,  209,  210,  200,  201,  202,  203,  211,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      204,  176,  212,  213,  208,  176,  176,  176,  214,  215,
      176,  212,  213,  214,  215,    0,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,

      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176
    } ;

static yyconst short int yy_nxt[982] =
    {   0,
      176,   21,   22,  166,   23,  167,   24,   21,   22,   27,
       23,  166,   24,   28,   27,   29,   30,   25,   28,   79,
       29,   30,   31,   25,   28,   79,   34,   31,   28,  124,
       34,  119,   80,  162,  120,  121,  122,  123,   80,  150,
      160,  150,   82,  151,  152,   32,  153,   82,  158,  155,
       32,   35,   36,   37,   36,   38,   35,   39,   40,   41,
       42,   35,   35,   43,   35,   44,   35,   45,   46,   47,
       48,   49,   50,   50,   50,   50,   51,   35,   52,   35,
       35,   50,   50,   50,   50,   50,   50,   50,   53,   54,
       55,   28,   28,   28,  152,  162,  136,   71,   71,  154,

      155,  109,  156,  151,  152,  110,  153,  106,  110,  103,
       57,   57,   57,   57,  127,  143,   72,   72,  143,   57,
       57,   57,   57,   57,   57,   57,   28,  136,  154,  155,
      125,  156,   81,  137,   76,  138,  103,  166,  124,  167,
      124,  124,  137,  114,  138,   57,   57,   57,   57,  109,
      103,  166,  168,  167,   57,   57,   57,   57,   57,   57,
       57,   58,   58,   58,   58,  107,  168,  106,  103,  102,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,  100,   99,   98,   97,   83,   58,   58,   58,   58,
       58,   58,   58,   28,   59,   60,   28,   61,   28,   28,

       62,   28,   28,   28,   28,   28,   63,   64,   65,   66,
       67,   28,   28,   28,   66,   66,   66,   66,   28,   68,
       28,   28,   28,   66,   66,   66,   66,   66,   66,   66,
       28,   28,   69,   73,   81,  158,  160,   77,   76,  176,
       74,  128,  132,  130,  134,   75,   75,   75,   75,  176,
      128,  132,  130,  134,   75,   75,   75,   75,   75,   75,
       75,   85,  103,  166,   86,  167,  176,  176,   87,   88,
       89,  103,  166,  176,  167,  176,  176,  176,  168,  176,
       90,  176,   91,   92,  176,   93,  176,  168,  176,  176,
      176,   94,   95,   96,  176,  176,  103,  166,  176,  167,

       94,   95,   96,   89,  176,  176,  176,  176,  176,  128,
      129,  130,  168,  176,  103,  166,  176,  167,  128,  129,
      130,  131,  176,  176,  176,  176,  176,  132,  133,  134,
      168,  103,  166,  176,  167,  176,  132,  133,  134,  135,
      176,  135,  103,  166,  136,  167,  176,  168,  103,  166,
      137,  167,  138,  103,  166,  176,  167,  176,  168,  137,
      176,  138,  103,  176,  168,  176,  176,  176,  139,  168,
      103,  166,  176,  167,  140,  141,  142,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  168,  144,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,

      145,  157,  176,  157,  176,  176,  158,  176,  176,  176,
      176,  176,  128,  176,  130,  176,  176,  176,  176,  176,
      176,  128,  176,  130,  159,  176,  159,  176,  176,  160,
      176,  176,  176,  176,  176,  132,  176,  134,  176,  176,
      176,  176,  176,  176,  132,  176,  134,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   56,   56,   56,   56,   56,

       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   78,   78,  176,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   84,
       84,  176,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,  101,  176,  176,  101,  101,
      104,  176,  176,  176,  176,  176,  176,  176,  176,  104,
      176,  176,  104,  104,  105,  176,  176,  105,  105,  108,

      108,  176,  176,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  111,  111,  111,  111,  176,
      111,  176,  111,  111,  176,  111,  111,  111,  111,  111,
      111,  112,  112,  176,  176,  176,  112,  113,  176,  176,
      176,  113,  113,  113,  113,  113,  113,  113,  176,  113,
      113,  113,  113,  115,  115,  176,  176,  176,  115,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  176,  116,  116,  116,  117,  117,  176,  117,  176,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  118,  118,  118,  118,  118,  118,  118,  118,  118,

      118,  118,  118,  118,  118,  118,  118,  126,  176,  176,
      126,  126,  143,  176,  176,  143,  176,  176,  143,  143,
      143,  143,  176,  176,  143,  176,  143,  146,  176,  176,
      176,  146,  146,  146,  146,  146,  146,  146,  176,  146,
      146,  146,  146,  147,  176,  176,  176,  147,  147,  147,
      147,  147,  147,  147,  176,  147,  147,  147,  147,  148,
      176,  176,  176,  148,  148,  148,  148,  148,  148,  148,
      176,  148,  148,  148,  148,  149,  176,  176,  176,  149,
      149,  149,  149,  149,  149,  149,  176,  149,  149,  149,
      149,  161,  161,  176,  176,  161,  161,  161,  161,  161,

      161,  161,  161,  161,  161,  161,  161,  163,  163,  163,
      163,  176,  163,  176,  163,  163,  176,  163,  163,  163,
      163,  163,  163,  164,  164,  176,  176,  176,  164,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  169,  169,  176,  176,  176,
      169,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  176,  170,  170,  170,  171,  176,  171,
      176,  176,  171,  176,  176,  171,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  173,  173,  173,  173,  173,  173,  173,  173,

      173,  173,  173,  173,  173,  173,  173,  173,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
       19,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176
    } ;

static yyconst short int yy_chk[982] =
    {   0,
        0,    1,    1,  168,    1,  168,    1,    2,    2,    3,
        2,  167,    2,    3,    4,    3,    3,    1,    4,   27,
        4,    4,    3,    2,    5,   79,    5,    4,    6,  124,
        6,   72,   27,  161,   72,   72,   72,   72,   79,  124,
      159,  124,  184,  125,  125,    3,  125,  184,  157,  156,
        4,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    9,   15,   16,  153,  139,  135,   15,   16,  127,

      127,  108,  127,  151,  151,  190,  151,  106,  190,  104,
        9,    9,    9,    9,   87,  205,   15,   16,  205,    9,
        9,    9,    9,    9,    9,    9,   10,  136,  154,  154,
       81,  154,   80,  136,   76,  136,  143,  143,   75,  143,
       74,   73,  136,   67,  136,   10,   10,   10,   10,   62,
      162,  162,  143,  162,   10,   10,   10,   10,   10,   10,
       10,   11,   11,   11,   11,   61,  162,   59,   57,   55,
       11,   11,   11,   11,   11,   11,   11,   12,   12,   12,
       12,   49,   48,   47,   46,   38,   12,   12,   12,   12,
       12,   12,   12,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   17,   31,  158,  160,   23,   21,   19,
       17,  158,  160,  158,  160,   17,   17,   17,   17,    0,
      158,  160,  158,  160,   17,   17,   17,   17,   17,   17,
       17,   44,  163,  163,   44,  163,    0,    0,   44,   44,
       44,  164,  164,    0,  164,    0,    0,    0,  163,    0,
       44,    0,   44,   45,    0,   45,    0,  164,    0,    0,
        0,   45,   45,   45,    0,    0,  165,  165,    0,  165,

       45,   45,   45,   89,    0,    0,    0,    0,    0,   89,
       89,   89,  165,    0,  169,  169,    0,  169,   89,   89,
       89,   92,    0,    0,    0,    0,    0,   92,   92,   92,
      169,  170,  170,    0,  170,    0,   92,   92,   92,   95,
        0,   95,  172,  172,   95,  172,    0,  170,  173,  173,
       95,  173,   95,  174,  174,    0,  174,    0,  172,   95,
        0,   95,  103,    0,  173,    0,    0,    0,  103,  174,
      175,  175,    0,  175,  103,  103,  103,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  175,  103,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

      103,  129,    0,  129,    0,    0,  129,    0,    0,    0,
        0,    0,  129,    0,  129,    0,    0,    0,    0,    0,
        0,  129,    0,  129,  133,    0,  133,    0,    0,  133,
        0,    0,    0,    0,    0,  133,    0,  133,    0,    0,
        0,    0,    0,    0,  133,    0,  133,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  180,  180,  180,  180,  180,

      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  183,  183,    0,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  185,
      185,    0,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  186,    0,    0,  186,  186,
      187,    0,    0,    0,    0,    0,    0,    0,    0,  187,
        0,    0,  187,  187,  188,    0,    0,  188,  188,  189,

      189,    0,    0,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  191,  191,  191,  191,    0,
      191,    0,  191,  191,    0,  191,  191,  191,  191,  191,
      191,  192,  192,    0,    0,    0,  192,  193,    0,    0,
        0,  193,  193,  193,  193,  193,  193,  193,    0,  193,
      193,  193,  193,  194,  194,    0,    0,    0,  194,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,    0,  195,  195,  195,  196,  196,    0,  196,    0,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  197,  197,  197,  197,  197,  197,  197,  197,  197,

      197,  197,  197,  197,  197,  197,  197,  198,    0,    0,
      198,  198,  199,    0,    0,  199,    0,    0,  199,  199,
      199,  199,    0,    0,  199,    0,  199,  200,    0,    0,
        0,  200,  200,  200,  200,  200,  200,  200,    0,  200,
      200,  200,  200,  201,    0,    0,    0,  201,  201,  201,
      201,  201,  201,  201,    0,  201,  201,  201,  201,  202,
        0,    0,    0,  202,  202,  202,  202,  202,  202,  202,
        0,  202,  202,  202,  202,  203,    0,    0,    0,  203,
      203,  203,  203,  203,  203,  203,    0,  203,  203,  203,
      203,  204,  204,    0,    0,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  204,  204,  204,  206,  206,  206,
      206,    0,  206,    0,  206,  206,    0,  206,  206,  206,
      206,  206,  206,  207,  207,    0,    0,    0,  207,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  209,  209,    0,    0,    0,
      209,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,    0,  210,  210,  210,  211,    0,  211,
        0,    0,  211,    0,    0,  211,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  213,  213,  213,  213,  213,  213,  213,  213,

      213,  213,  213,  213,  213,  213,  213,  213,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst short int yy_rule_linenum[60] =
    {   0,
      149,  152,  156,  159,  162,  167,  172,  177,  194,  197,
      202,  208,  214,  219,  225,  229,  233,  237,  241,  245,
      249,  253,  257,  261,  268,  274,  279,  286,  293,  300,
      307,  318,  329,  336,  347,  351,  358,  362,  364,  371,
      372,  373,  374,  375,  376,  378,  384,  453,  459,  464,
      471,  478,  483,  488,  495,  502,  509,  513,  518
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../../../libs/libFreeMat/Lexer.lxx"
#define INITIAL 0
#line 2 "../../../libs/libFreeMat/Lexer.lxx"
// Copyright (c) 2002, 2003 Samit Basu
// 
// Permission is hereby granted, free of charge, to any person obtaining a 
// copy of this software and associated documentation files (the "Software"), 
// to deal in the Software without restriction, including without limitation 
// the rights to use, copy, modify, merge, publish, distribute, sublicense, 
// and/or sell copies of the Software, and to permit persons to whom the 
// Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included 
// in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
// DEALINGS IN THE SOFTWARE.

#include "AST.hpp"
#define YYSTYPE FreeMat::ASTPtr	
#include "Parser.h"
extern YYSTYPE yylval;
#include "Reserved.hpp"
#include "Exception.hpp"
#include <stdlib.h>

using namespace FreeMat;

extern int lineNumber;

reservedWordStruct ts, *p;
 
  // These are the possible contexts in which end's can occur. 
  typedef enum {
    context_for,
    context_while,
    context_if,
    context_try,
    context_switch,
    context_index,
    context_matrix,
    context_cell,
    context_error
  } end_context;

  int stackCount;
  int stateStack[1000];
  int contextCount;
  end_context contextStack[1000]; 
  end_context thisContext;
  int rettoken;
  int lineNumber;
  int continuationCount;
  bool firstToken;
  bool minusisneg;
  
  void pushState(int state) {
    stateStack[stackCount] = state;
    printf("push top state is %d\n",stateStack[stackCount]);
    stackCount++;
  }
  
  int popState() {
    if (stackCount < 1)
	return 0;
    stackCount--;
    printf("pop top state is %d\n",stateStack[stackCount]);
    return stateStack[stackCount];
  }
  
  int topState() {
    return stateStack[stackCount-1];
  }
 
  void pushContext(end_context context) { 
    contextStack[contextCount] = context;
    contextCount++;
  }

  end_context popContext(char t) {
    if (contextCount < 1) {
      switch (t) {
      case ')':
	throw Exception("unexpected ')' encountered");
      case '}':
	throw Exception("unexpected '}' encountered");
      case ']':
	throw Exception("unexpected ']' encountered");
      case 'x':
	throw Exception("unexpected 'end' encountered");
      }
    } 
    contextCount--;
    return contextStack[contextCount];
  }

  end_context topContext() {
    return contextStack[contextCount-1];
  }

#define IdentDereference 1

#define TransposeCheck 2

#define Scanning 3

#define SpecialSyntax 4

#define SpecialSyntaxStart 5

#define SpecialSyntaxArgs 6

#define str 7

#define Mscan 8

#line 780 "../../../libs/libFreeMat/Lexer.cxx"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 144 "../../../libs/libFreeMat/Lexer.lxx"


	char string_buf[4095];
	char *string_buf_ptr;

#line 937 "../../../libs/libFreeMat/Lexer.cxx"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 177 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 941 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */

		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 60 )
				fprintf( stderr, "--accepting rule at line %d (\"%s\")\n",
				         yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 60 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 61 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 149 "../../../libs/libFreeMat/Lexer.lxx"
{
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 152 "../../../libs/libFreeMat/Lexer.lxx"
{
  lineNumber++;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 156 "../../../libs/libFreeMat/Lexer.lxx"
{
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 159 "../../../libs/libFreeMat/Lexer.lxx"
{
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 162 "../../../libs/libFreeMat/Lexer.lxx"
{
  yyless(0);
  BEGIN(SpecialSyntax);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 167 "../../../libs/libFreeMat/Lexer.lxx"
{
  yyless(0);
  BEGIN(SpecialSyntaxStart);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 172 "../../../libs/libFreeMat/Lexer.lxx"
{
  yyless(0);
  BEGIN(Scanning);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 177 "../../../libs/libFreeMat/Lexer.lxx"
{
  /* Check for a reserved word... */
  ts.word = yytext;
  p = (reservedWordStruct*)
    bsearch(&ts,reservedWord,RESWORDCOUNT,
	    sizeof(reservedWordStruct),
	    compareReservedWord);
  if (p!=NULL) {
    yyless(0);
    BEGIN(Scanning);
  } else {
    yylval = new AST(id_node,yytext);
    BEGIN(SpecialSyntaxArgs);  
    return SPECIALCALL;
  }
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 194 "../../../libs/libFreeMat/Lexer.lxx"
{
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 197 "../../../libs/libFreeMat/Lexer.lxx"
{
  yylval = new AST(string_const_node,yytext);
  return STRING;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 202 "../../../libs/libFreeMat/Lexer.lxx"
{
  yytext[yyleng-1] = 0;
  yylval = new AST(string_const_node,yytext+1);
  return STRING;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 208 "../../../libs/libFreeMat/Lexer.lxx"
{
  lineNumber++;
  BEGIN(INITIAL);
  return ENDQSTMNT;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 214 "../../../libs/libFreeMat/Lexer.lxx"
{
  BEGIN(INITIAL);
  return ENDQSTMNT;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 219 "../../../libs/libFreeMat/Lexer.lxx"
{
  lineNumber++;
  BEGIN(INITIAL);
  return ENDSTMNT;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 225 "../../../libs/libFreeMat/Lexer.lxx"
{
  return EQ;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 229 "../../../libs/libFreeMat/Lexer.lxx"
{			
  return DOTTIMES;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 233 "../../../libs/libFreeMat/Lexer.lxx"
{
  return DOTRDIV;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 237 "../../../libs/libFreeMat/Lexer.lxx"
{
  return DOTLDIV;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 241 "../../../libs/libFreeMat/Lexer.lxx"
{			
  return LE;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 245 "../../../libs/libFreeMat/Lexer.lxx"
{
  return GE;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 249 "../../../libs/libFreeMat/Lexer.lxx"
{
  return NE;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 253 "../../../libs/libFreeMat/Lexer.lxx"
{
  return DOTPOWER;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 257 "../../../libs/libFreeMat/Lexer.lxx"
{
  return DOTTRANSPOSE;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 261 "../../../libs/libFreeMat/Lexer.lxx"
{
  lineNumber++;
  firstToken = true;
  BEGIN(INITIAL);
  return ENDQSTMNT;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 268 "../../../libs/libFreeMat/Lexer.lxx"
{
  firstToken = true;
  BEGIN(INITIAL);
  return ENDQSTMNT;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 274 "../../../libs/libFreeMat/Lexer.lxx"
{
  BEGIN(Scanning);
  return ',';
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 279 "../../../libs/libFreeMat/Lexer.lxx"
{
  lineNumber++;
  firstToken = true;
  BEGIN(INITIAL);
  return ENDSTMNT;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 286 "../../../libs/libFreeMat/Lexer.lxx"
{
  pushState(YYSTATE);
  pushContext(context_index);
  BEGIN(Scanning);
  return '(';
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 293 "../../../libs/libFreeMat/Lexer.lxx"
{
  pushState(YYSTATE);
  pushContext(context_cell);
  BEGIN(Mscan);
  return '{';
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 300 "../../../libs/libFreeMat/Lexer.lxx"
{
  pushState(YYSTATE);
  pushContext(context_matrix);
  BEGIN(Mscan);
  return '[';
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 307 "../../../libs/libFreeMat/Lexer.lxx"
{
  popContext(')');
  if (topState() == Scanning) {
    BEGIN(TransposeCheck);
    return ')'; 
  } else {
    BEGIN(popState());
    return REFRPAREN;
  }
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 318 "../../../libs/libFreeMat/Lexer.lxx"
{
  popContext('}');
  if (topState() == Scanning) {
    BEGIN(TransposeCheck);
    return '}';
  } else {
    BEGIN(popState());
    return REFRBRACE;
  }
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 329 "../../../libs/libFreeMat/Lexer.lxx"
{
  popContext(']');
  pushState(YYSTATE);
  BEGIN(TransposeCheck);
  return ']';
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 336 "../../../libs/libFreeMat/Lexer.lxx"
{
  int i;
  char *yycopy = strdup(yytext);
  for (i=yyleng-1;i>=0;--i) 
    if (i != 1)
      unput(yycopy[i]);
    else
      unput(',');
  free(yycopy);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 347 "../../../libs/libFreeMat/Lexer.lxx"
{
  /* skip */
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 351 "../../../libs/libFreeMat/Lexer.lxx"
{
  lineNumber++;
  continuationCount++;
  firstToken = false;
  BEGIN(Scanning);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 358 "../../../libs/libFreeMat/Lexer.lxx"
{
  /* skip */
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 362 "../../../libs/libFreeMat/Lexer.lxx"
string_buf_ptr = string_buf; BEGIN(str);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 364 "../../../libs/libFreeMat/Lexer.lxx"
{
	BEGIN(Scanning); 
	*string_buf_ptr = '\0';
	yylval = new AST(string_const_node,string_buf);
	return STRING;
	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 371 "../../../libs/libFreeMat/Lexer.lxx"
*string_buf_ptr++ = 10;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 372 "../../../libs/libFreeMat/Lexer.lxx"
*string_buf_ptr++ = 9;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 373 "../../../libs/libFreeMat/Lexer.lxx"
*string_buf_ptr++ = 13;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 374 "../../../libs/libFreeMat/Lexer.lxx"
*string_buf_ptr++ = 8;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 375 "../../../libs/libFreeMat/Lexer.lxx"
*string_buf_ptr++ = 12;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 376 "../../../libs/libFreeMat/Lexer.lxx"
*string_buf_ptr++ = yytext[1];
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 378 "../../../libs/libFreeMat/Lexer.lxx"
{
                   char *yptr = yytext;
                   while ( *yptr )
                           *string_buf_ptr++ = *yptr++;
                 }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 384 "../../../libs/libFreeMat/Lexer.lxx"
{
  /* Search for the identifier in the keyword table */
  ts.word = yytext;
  p = (reservedWordStruct*) 
    bsearch(&ts,reservedWord,RESWORDCOUNT,
	    sizeof(reservedWordStruct),
	    compareReservedWord);
  if (p==NULL) {
    pushState(YYSTATE);
    BEGIN(IdentDereference);
    yylval = new AST(id_node,yytext); 
    return IDENT;
  } else {
    // Check for reserved words that trigger end-context changes
    rettoken = p->token;
    switch (p->token) {
    case ELSEIF:
      BEGIN(Mscan);
      break;
    case CASE:
      BEGIN(Mscan);
      break;
    case SWITCH:
      pushContext(context_switch);
      BEGIN(Mscan);
      break;
    case FOR:
      pushContext(context_for);
      BEGIN(Mscan);
      break;
    case WHILE:
      pushContext(context_while);
      BEGIN(Mscan);
      break;
    case TRY:
      pushContext(context_try);
      break;
    case IF:
      pushContext(context_if);
      BEGIN(Mscan);
      break;
    case END:
      thisContext = popContext('x');
      switch (thisContext) {
      case context_for:
	rettoken = ENDFOR;
	break;
      case context_switch:
	rettoken = ENDSWITCH;
	break;
      case context_while:
	rettoken = ENDWHILE;
	break;
      case context_try:
	rettoken = ENDTRY;
	break;
      case context_if:
	rettoken = ENDIF;
	break;
      default:
	pushContext(thisContext);
	rettoken = END;
      }
    }
    yylval = new AST(reserved_node,p->ordinal);
    return rettoken;
  }
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 453 "../../../libs/libFreeMat/Lexer.lxx"
{
  lineNumber++;
  continuationCount++;
  firstToken = false;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 459 "../../../libs/libFreeMat/Lexer.lxx"
{
  yylval = new AST(id_node,yytext+1);
  return FIELD;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 464 "../../../libs/libFreeMat/Lexer.lxx"
{
  pushState(IdentDereference);
  pushContext(context_index);
  BEGIN(Scanning);
  return REFLPAREN;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 471 "../../../libs/libFreeMat/Lexer.lxx"
{
  pushState(IdentDereference);
  pushContext(context_cell);
  BEGIN(Scanning);
  return REFLBRACE;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 478 "../../../libs/libFreeMat/Lexer.lxx"
{
  BEGIN(popState());
  return *yytext;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 483 "../../../libs/libFreeMat/Lexer.lxx"
{
  unput(yytext[0]);
  BEGIN(popState());
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 488 "../../../libs/libFreeMat/Lexer.lxx"
{
  pushState(YY_START);
  BEGIN(TransposeCheck);
  yylval = new AST(const_float_node,yytext);
  return NUMERIC;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 495 "../../../libs/libFreeMat/Lexer.lxx"
{
  pushState(YY_START);
  BEGIN(TransposeCheck);
  yylval = new AST(const_double_node,yytext);
  return NUMERIC;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 502 "../../../libs/libFreeMat/Lexer.lxx"
{
  pushState(YY_START);
  BEGIN(TransposeCheck);
  yylval = new AST(const_int_node,yytext);
  return NUMERIC;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 509 "../../../libs/libFreeMat/Lexer.lxx"
{
  return *yytext;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 513 "../../../libs/libFreeMat/Lexer.lxx"
{
  BEGIN(popState());
  return *yytext;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 518 "../../../libs/libFreeMat/Lexer.lxx"
{
  BEGIN(popState());
  unput(yytext[0]);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 523 "../../../libs/libFreeMat/Lexer.lxx"
ECHO;
	YY_BREAK
#line 1596 "../../../libs/libFreeMat/Lexer.cxx"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IdentDereference):
case YY_STATE_EOF(TransposeCheck):
case YY_STATE_EOF(Scanning):
case YY_STATE_EOF(SpecialSyntax):
case YY_STATE_EOF(SpecialSyntaxStart):
case YY_STATE_EOF(SpecialSyntaxArgs):
case YY_STATE_EOF(str):
case YY_STATE_EOF(Mscan):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 177 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 177 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 176);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 523 "../../../libs/libFreeMat/Lexer.lxx"


int yywrap() {
  return 1;
}

namespace FreeMat {

  void setLexBuffer(char *buffer) {
    stackCount = 0;
    stateStack[0] = 0;
    contextCount = 0;
    lineNumber = 0;
    continuationCount = 0;;
//    YY_FLUSH_BUFFER;
//    BEGIN(INITIAL);
    BEGIN(0);
    firstToken = true;
    yy_scan_string(buffer);
  }
  
  void setLexFile(FILE *fp) {
    stackCount = 0;
    stateStack[0] = 0;
    contextCount = 0;
    lineNumber = 0;
//    YY_FLUSH_BUFFER;
    firstToken = true;
//    BEGIN(INITIAL);
    BEGIN(0);
    yyrestart(fp);
  }
  
  int getContinuationCount() {
    return continuationCount;
  }

  bool lexCheckForMoreInput(int ccount) {
    // Scan the command line
//    while (yylex() > 0);
    while (yylex() > 0) {
	printf("token = %s\r\n",yytext);
   }
    return (((contextCount > 0) && (stackCount == 0)) || (continuationCount > ccount));
  }
  
  void lexSetAdditionalInput(char *buffer) {
    continuationCount = 0;
    firstToken = true;
    yy_scan_string(buffer);
  }    
}
