######################################################################
# Automatically generated by qmake (1.07a) Sun May 15 17:05:49 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += TermWidget.h
SOURCES += TermWidget.cpp
