Import('env')
list = Split("""cfftb1.c
cfftb.c
cfftf1.c
cfftf.c
cffti1.c
cffti.c
cpassb2.c
cpassb3.c
cpassb4.c
cpassb5.c
cpassb.c
cpassf2.c
cpassf3.c
cpassf4.c
cpassf5.c
cpassf.c
zfftb1.c
zfftb.c
zfftf1.c
zfftf.c
zffti1.c
zffti.c
zpassb2.c
zpassb3.c
zpassb4.c
zpassb5.c
zpassb.c
zpassf2.c
zpassf3.c
zpassf4.c
zpassf5.c
zpassf.c""")
Library('FFTPack', list)

