######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 29 21:45:48 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += term2.hpp
SOURCES += term2.cpp
