function x = test_expr1
  a = 32;
  b = 64;
  c = a + b;
  a(64) = c;
  d = a(end);
  a = 'hello';
  b = a(3);
  p = {1,2,3,4};
  c = p{2};
  p = {1,2,3,a};
  c = p{4}(5);
  b = struct('name',p);
  o = b(4).name(5);
  o = b(4).name(end);
  o = b(end).name(end);
  k.foo = 5;
  l(8).foo{5} = 'hello';
  a = test_expr1_helper;
  [a,b,c,d] = test_expr1_helper;
  z(4).lopper = 5;
  [z.lopper] = test_expr1_helper;
  x = 1;
  
function [a,b,c,d,e] = test_expr1_helper
a = 1;
b = 2;
c = 3;
d = 4;
e = 5;
