#!/bin/sh

# Script to regenerate the contents of the help
# directory, and then update the filelist for 
# automake.  It takes three arguments:
#   makehelp <buildpath> <sourcepath>
if test x"$1" == x"--help"; then
  echo "makehelp <buildpath> <sourcepath>"
  exit
fi
buildpath=$1
sourcepath=$2
cwd=`pwd`;
cd $buildpath
buildpath=`pwd`
cd $cwd
cd $sourcepath
sourcepath=`pwd`
cd $cwd
echo "Removing current help directory"
rm -rf $sourcepath/help
rm -rf tmp
mkdir tmp
cd tmp
echo "Building help files"
$buildpath/tools/helpgen/helpgen $sourcepath
cp *.jpg $sourcepath/help/html/.
cp *.png $sourcepath/help/html/.
cp *.jpg $sourcepath/help/latex/.
cp *.png $sourcepath/help/latex/.
cdir=`pwd`
cd $sourcepath/help/latex
pdflatex main.tex
pdflatex main.tex
cd $cwd
echo "Cleaning up"
rm -rf tmp
rm $sourcepath/manifest.am
echo "Writing manifest"
htmlhelpfiles=`cd $sourcepath && find help/html -type f -printf "%p "`
texthelpfiles=`cd $sourcepath && find help/text -type f -printf "%p "`
helpmfiles=`cd $sourcepath && find help/MFiles -type f -printf "%p "`
coremfiles=`cd $sourcepath && find MFiles -type f -printf "%p "`
pkgfiles=`cd $sourcepath && find extern -type f -printf "%p "`
coremfiles=`echo $coremfiles | sed -e 's/[^ ]*\.svn[^ ]*[ ]*//g'`
coremfiles=`echo $coremfiles | sed -e 's/[^ ]*~//g'`
coremfiles=`echo $coremfiles | sed -e 's/#[^#]*#//g'`
pkgfiles=`echo $pkgfiles | sed -e 's/[^ ]*\.svn[^ ]*[ ]*//g'`
echo "EXTRA_DIST = $pkgfiles $htmlhelpfiles $texthelpfiles $helpmfiles $coremfiles help/latex/main.pdf " > $sourcepath/manifest.am 
echo "nobase_resource_DATA = $htmlhelpfiles $texthelpfiles $helpmfiles help/latex/main.pdf " >> $sourcepath/manifest.am
