#!/bin/sh

# Script to regenerate the contents of the help
# directory, and then update the filelist for 
# automake.  It takes three arguments:
#   makehelp <buildpath> <sourcepath>
if test x"$1" == x"--help"; then
  echo "makehelp <buildpath> <sourcepath>"
  exit
fi
buildpath=$1
sourcepath=$2
cwd=`pwd`;
cd $buildpath
buildpath=`pwd`
cd $cwd
cd $sourcepath
sourcepath=`pwd`
cd $cwd
cd $sourcepath/help/latex
pdflatex main.tex
pdflatex main.tex
pdflatex main.tex
cd $cwd
echo "Cleaning up"
rm -rf tmp
rm $sourcepath/manifest.am
echo "Writing manifest"
htmlhelpfiles=`cd $sourcepath && find help/html -type f -printf "%p "`
texthelpfiles=`cd $sourcepath && find help/text -type f -printf "%p "`
testfiles=`cd $sourcepath && find help/test -type f -printf "%p "`
helpmfiles=`cd $sourcepath && find help/toolbox -type f -printf "%p "`
coremfiles=`cd $sourcepath && find toolbox -type f -printf "%p "`
coremfiles=`echo $coremfiles | sed -e 's/[^ ]*\.svn[^ ]*[ ]*//g'`
coremfiles=`echo $coremfiles | sed -e 's/[^ ]*~//g'`
coremfiles=`echo $coremfiles | sed -e 's/#[^#]*#//g'`
echo "EXTRA_DIST = $htmlhelpfiles $texthelpfiles $helpmfiles $coremfiles help/latex/main.pdf " > $sourcepath/manifest.am 
echo "nobase_resource_DATA = $htmlhelpfiles $texthelpfiles $helpmfiles help/latex/main.pdf " >> $sourcepath/manifest.am
