env = Environment(tools=['default','qt'])
#DumbTerminal.cpp
list = Split(""" 
MainApp.cpp
Terminal.cpp
SocketCB.cpp
main.cpp""")
env.Append(CPPPATH = ['.','../libs/libFreeMat','../libs/libXP','../libs/libCore','../libs/libFN','../libs/libGraphics'])
libdirlist = Split("""
../libs/libARPACK
../libs/libCore
../libs/libffi
../libs/libFFTPack
../libs/libGraphics
../libs/libUMFPACK
../libs/libUMFPACK/AMD
../libs/libFN
../libs/libFreeMat
../libs/libXP
""")
liblist = Split("""
Core
FFTPack
FN
FreeMat
ffi
Graphics
XP
ARPACK
UMFPACKzi
UMFPACKdi
AMD
blas
lapack
curses
""")
env.Prepend(LIBPATH = libdirlist)
env.Prepend(LIBS = liblist)
env.Program('FreeMat',list)
