a = axes;
dmo;
set(2,'children',a);
set(a,'color','w');
set(a,'parent',2);
set(a,'xlim',[-1,1]);
set(a,'ylim',[-1,1]);
set(a,'zlim',[-1,1]);
set(a,'xtick',linspace(-1,1,4));
set(a,'ytick',linspace(-1,1,4));
set(a,'ztick',linspace(-1,1,4));
set(a,'xticklabel','-1|0.25|0.25|1');
set(a,'yticklabel','-1|0.25|0.25|1');
set(a,'zticklabel','-1|0.25|0.25|1');
set(a,'xgrid','on');
set(a,'ygrid','on');
set(a,'zgrid','on');
set(a,'xcolor','k');
set(a,'ycolor','k');
set(a,'zcolor','k');
set(a,'tickdir','out');
f = text('string','X Time','fontsize',12,'parent',a,'horiz','center','vert','middle');
set(a,'xlabel',f);
g = text('string','Y Time','fontsize',12,'parent',a,'horiz','center','vert','middle');
set(a,'ylabel',g);
h = text('string','Z Time','fontsize',12,'parent',a,'horiz','center','vert','middle');
set(a,'zlabel',h);
k = text('string','Hello','fontsize',20,'parent',a,'horiz','center','vert','top','position',[0.5,1,0]);
set(a,'title',k);
set(a,'cameraposition',[-1,-1,-1]);
%set(a,'outerposition',[0.1,0.1,0.5,0.5]);
ts = linspace(-pi,pi,100);
xs = cos(ts);
ys = sin(ts);
zs = ts/pi;
p = line('xdata',xs,'ydata',ys,'zdata',zs,'parent',a,'marker','square','markeredgecolor','r','markerfacecolor','g');
set(a,'children',[get(a,'children'),p]);

