x = linspace(0,1,25);
red = x'*x;
green = (fliplr(x)')*fliplr(x);
blue = ones(25,1)*x;
k(:,:,1) = red;
k(:,:,2) = green;
k(:,:,3) = blue;
xdata = [1,25];
ydata = [1,25];
a = gca;
set(a,'xlim',[1,25]);
set(a,'xlimmode','manual');
set(a,'ylim',[1,25]);
set(a,'ylimmode','manual');
h = image('cdata',k,'xdata',xdata,'ydata',ydata,'parent',a);
set(a,'children',[get(a,'children'),h]);
