Import('env')
list = Split("""Cast.cpp 
Constructors.cpp 
FFT.cpp 
StringOps.cpp 
Transcendental.cpp 
Trigonometric.cpp 
Misc.cpp 
Constants.cpp 
Directory.cpp 
Analyze.cpp 
Utils.cpp 
IO.cpp 
Inspect.cpp 
Random.cpp 
LoadCore.cpp 
helpwindow.cpp
MPIWrap.cpp 
RanLib.cpp """)
env.Append(CPPPATH = ['.','../libFreeMat','../libXP'])
env.Library('Core', list)

