######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 4 19:44:03 2007
######################################################################

TEMPLATE = app
TARGET = 
INCLUDEPATH += .

# Input
SOURCES += serv.cpp 
QT += network
